INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('UNIVAG', 'Várzea Grande', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIVALE MG', 'Governador Valares', 'MG', 'Sudeste', 'Privada', false, false, false, 'ENEM'),
  ('UNIVALI', 'Itajaí', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIVAR', 'Barra dos Garças', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVAS', 'Pouso Alegre', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVASF', 'Petrolina', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UNIVASF', 'Petrolina', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UNIVATES', 'Lajeado', 'Rio Grande Do Sul', 'Sul', 'Privada', true, false, false, 'ENEM'),
  ('Universidade de Vassouras', 'Vassouras', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('Univértix', 'Matipó', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('UNIVILLE', 'Joinville', 'SC', 'Sul', 'Privada', false, false, false, 'Análise'),
  ('UNIVS', 'Icó', 'CE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNOCHAPECO', 'Chapecó', 'SC', 'Sul', 'Pública', false, false, false, 'Prova'),
  ('UNOESC', 'Joaçaba', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNOESTE', 'Guarujá', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNOESTE', 'Presidente Prudente', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UnP', 'Natal', 'Rio Grande Do Norte', 'Nordeste', 'Privada', true, false, false, 'Análise Curricular'),
  ('UP', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UPE', 'Garanhuns', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPE', 'Recife', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPE', 'Serra Talhada', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPF', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('URI ERECHIM', 'Erechim', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('USCS', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USCS', 'São Caetano do Sul', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USF', 'Bragança Paulista', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USJT', 'São Paulo', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('USP', 'Bauru', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USP', 'Ribeirão Preto', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USP', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UVA', 'Rio de Janeiro', 'RJ', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UVV', 'Vila Velha', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('ZARNS', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova');