INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('FAM', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Enem'),
  ('FAME', 'Barbacena', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMEJIPA', 'Ji-Paraná', 'RO', 'Oeste', 'Privada', true, false, false, 'Prova'),
  ('FAMEMA', 'Marília', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('FAMENE', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMERP', 'São Jose do Rio Preto', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('FAMESC', 'Bom Jesus do Itabapoana', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMETRO', 'Manaus', 'AM', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('FAMEU', 'Uberlândia', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMINAS', 'Muriaé', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMINAS', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMP', 'Mineiros', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAP', 'Araripina', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FAS', 'Lauro De Freitas', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FASA', 'Vitória Da Conquista', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASA', 'Itabuna', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASB', 'Barreiras', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASEH', 'Vespasiano', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FASM', 'Muriaé', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMMG', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMPB', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FCMS', 'Juiz De Fora', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMSCSP', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMTR', 'Três Rios', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FEEVALE', 'Novo Hamburgo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular/Enem'),
  ('FEMA', 'Assis', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FEPAR', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FESAR', 'Redenção', 'PA', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FICSAE', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FIMCA', 'Porto Velho', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FIP', 'Patos', 'PB', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FIP', 'Montes Claros', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FIP', 'Guanambi', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FMABC', 'Santo André', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FMC', 'Campos dos Goytacazes', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMIT', 'Itajubá', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMJ', 'Jundiaí', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FMO', 'Olinda', 'PE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('FMP', 'Petrópolis', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMPFM', 'Mogi Guaçu', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('FPP', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FPS', 'Recife', 'PE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('FSLM', 'Araras', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FSLM', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FSM', 'Cajazeiras', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FUNEPE', 'Penápolis', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FUNORTE', 'Montes Claros', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FURB', 'Blumenau', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FURG', 'Rio Grande', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Prova'),
  ('HONPAR', 'Arapongas', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular');