INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('AFYA PARAÍBA', 'Cabedelo', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('IDEA MEDICINA', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNILAGOS', 'Araruama', 'RJ', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('AESGA', 'Garanhuns', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('AFYA SÃO LUCAS', 'Porto Velho', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('AGES', 'Irecê', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise'),
  ('AGES', 'Jacobina', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise'),
  ('ASCES-UNITA', 'Caruaru', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('Atenas', 'Passos', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Atenas', 'Paracatu', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('Atenas', 'Sete Lagoas', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('CAMPOREAL', 'Guarapuava', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('CEI', 'Campo Mourão', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('CESMAC', 'Maceió', 'AL', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('CESUPA', 'Belém', 'PA', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('CET', 'Teresina', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('CEUB', 'Brasília', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('CEUCLAR', 'Rio Claro', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('EBMSP', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Vestibular'),
  ('EDUFOR', 'São Luis', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('EMESCAM', 'Vitória', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('EMSM', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('ENIAC', 'Guarulhos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('ESCS', 'Brasília', 'DF', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('Estácio', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Alagoinhas', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Canindé', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Juazeiro', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Juazeiro do Norte', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Quixadá', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Cittá', 'Rio De Janeiro', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Jaraguá Do Sul', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Presidente Vargas', 'Rio De Janeiro', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Castanhal', 'PA', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Cáceres', 'MT', 'Centro-Oeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Teresina', 'PI', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Açailandia', 'MA', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAB/UNINORTE', 'Rio Branco', 'AC', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACENE', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACERES', 'São José do Rio Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FACI', '-', 'ES', 'Sudeste', 'Privada', false, false, false, ''),
  ('FACIMED', 'Cacoal', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACIMPA', 'Marabá', 'PA', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('FACISB', 'Barretos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FADIP', 'Ponte Nova', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAE', 'São João Da Boa Vista', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAG', 'Cascavel', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FAGOC', 'Ubá', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAHESP/iESVAP', 'Parnaíba', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAI', 'Adamantina', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova');