INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('UESB', 'Jequié', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UESB', 'Vitória Da Conquista', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UESC', 'Ilheus', 'BA', 'Nordeste', 'Pública', true, false, false, 'Enem'),
  ('UESPI', 'Teresina', 'PI', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UFAC', 'Rio Branco', 'AC', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFAL', 'Maceió', 'AL', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFAL', 'Arapiraca', 'AL', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFAM', 'Coari', 'AM', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFAM', 'Manaus', 'AM', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFBA', 'Salvador', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova/Análise'),
  ('UFBA', 'Vitória da Conquista', 'BA', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFBM', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UFC', 'Fortaleza', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFC', 'Sobral', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCA', 'Barbalha', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCAT', 'Goiânia', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFCG', 'Cajazeiras', 'PB', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCG', 'Campina Grande', 'PB', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCSPA', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UFERSA', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFES', 'Vitória', 'ES', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFF', 'Niteroi', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UFFS', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UFFS', 'Chapecó', 'SC', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UFG', 'Goiânia', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFG', 'Jataí', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFGD', 'Itahum', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UFJ', 'Riachuelo', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFJF', 'Governador Valares', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFJF', 'Juiz De Fora', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFLA', 'Lavras', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'Pinheiro', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'Imperatriz', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'São Luís', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMG', 'Belo Horizonte', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFMS', 'Campo Grande', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UFMS', 'Três Lagoas', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UFMT', 'Cuiabá', 'MT', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFMT', 'Sinop', 'MT', 'Centro-Oeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFOB', 'Barreiras', 'BA', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFOP', 'Ouro Preto', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFPA', 'Belém', 'PA', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFPB', 'João Pessoa', 'PB', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFPE', 'Recife', 'PE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPE', 'Caruaru', 'PE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPel', 'Pelotas', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'ENEM'),
  ('UFPI', 'Parnaíba', 'PI', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFPI', 'Teresina', 'PI', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPI', 'Picos', 'PI', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPR', 'Toledo', 'PR', 'Sul', 'Pública', true, false, false, 'Prova');