INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('UFPR', 'Curitiba', 'PR', 'Sul', 'Pública', true, false, false, 'Prova'),
  ('UFR', 'Rondonópolis', 'MT', 'Centro-Oeste', 'Pública', false, false, false, ''),
  ('UFRB', 'Santo Antônio de Jesus', 'BA', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFRGS', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFRJ', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFRJ', 'Macaé', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFRN', 'Natal', 'Rio Grande Do Norte', 'Nordeste', 'Pública', true, false, false, 'Enem'),
  ('UFRN', 'Caicó', 'Rio Grande Do Norte', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFRR', 'Boa Vista', 'RR', 'Norte', 'Pública', true, false, false, 'Enem'),
  ('UFS', 'Lagarto', 'SE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFS', 'São Cristóvão', 'SE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFSBA', 'Teixeira De Freitas', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFSC', 'Araranguá', 'SC', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFSC', 'Florianópolis', 'SC', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFSCAR', 'São Carlos', 'SP', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFSJ', 'São João Del Rey', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFSJ', 'Divinópolis', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFSM', 'Santa Maria', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UFT', 'Palmas', 'TO', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UFT', 'Araguaína', 'TO', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UFTM', 'Uberaba', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFU', 'Uberlândia', 'MG', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('UFV', 'Viçosa', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFVJM', 'Diamantina', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFVJM', 'Teófilo Otoni', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFVSF', 'Paulo Afonso', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UIt', 'Itaúna', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('ULBRA', 'Canoas', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UMC', 'Mogi das Cruzes', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNA', 'Tucurí', 'PA', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('UNAERP', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UnB', 'Brasília', 'DF', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UnC', 'Mafra', 'SC', 'Sul', 'Privada', true, false, false, 'Análise Curricular'),
  ('UNCISAL', 'Maceió', 'AL', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UNDB', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNEB', 'Salvador', 'BA', 'Nordeste', 'Pública', true, false, false, 'Enem e Análise Curricular'),
  ('Unec', 'Caratinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNECEPLAC', 'Brasilia', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Enem'),
  ('UNEMAT', 'Caceres', 'MT', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNESC', 'Criciúma', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNESC', 'Colatina', 'ES', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNESP', 'Botucatu', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('UNESUL', 'Eunápolis', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNEX', 'Vitória da Conquista', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise Curricular'),
  ('UNI-BH', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNI-FACEF', 'Franca', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UNIARA', 'Araraquara', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIARP', 'Caçador', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNIC', 'Cuiabá', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNICAMP', 'Campinas', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova');