INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('UNICAP', 'Recife', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICENTRO', 'Guarapuava', 'PR', 'Sul', 'Pública', false, false, false, 'Enem'),
  ('UNICEPLAC', 'Brasília', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNICERRADO', 'Goiatuba', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNICESUMAR', 'Maringá', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNICESUMAR', 'Corumbá', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Privada', true, false, false, 'Análise Curricular'),
  ('UNICEUB', 'Brasilia', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNICEUMA', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICEUMA', 'Imperatriz', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICHRISTUS', 'Fortaleza', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICID', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Unidavi', 'Rio do Sul', 'SC', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIDEP', 'Pato Branco', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIDERP', 'Campo Grande', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIDOMPEDRO', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIEURO', 'Taguatinga', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UniEVANGELICA', 'Anápolis', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAA', 'Valença', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFACCAMP', 'Campo Limpo Paulista', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova/Análise Curricular'),
  ('UNIFACEMP', 'Santo Antônio de Jesus', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFACIG', 'Manhuaçu', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFACISA', 'Campina Grande', 'PB', 'Nordeste', 'Privada', false, false, false, 'Enem'),
  ('UNIFACS', 'Salvador', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFADRA', 'Dracena', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAESF', 'Floriano', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFAJ', 'Jaguariúna', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFAL', 'Alfenas', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UNIFAMAZ', 'Belém', 'PA', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFAN', 'Aparecida De Goiania', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAP', 'Macapá', 'AP', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UNIFEBE', 'Brusque', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIFEBE', 'Brusque', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIFENAS', 'Alfenas', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFENAS-BH', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFESO', 'Teresópolis', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFESP', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UNIFEV', 'Votuporanga', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFG', 'Guanambi', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFIMES', 'Mineiros', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIFIMES', 'Trindade', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIFIPA', 'Catanduva', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFOA', 'Volta Redonda', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFOR', 'Fortaleza', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFRA', 'Santa Maria', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Vestibular'),
  ('UNIFRAN', 'Franca', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFTC', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFUNEC', 'Santa Fé do Sul', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIG', 'Itaperuna', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIG', 'Nova Iguaçu', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIGRANRIO', 'Duque De Caxias', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular');