INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('UNIGRANRIO', 'Barra da Tijuca', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIJUI', 'Ijuí', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Enem'),
  ('UNILA', 'Foz do Iguaçu', 'PR', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UNILAGO', 'São Jose do Rio Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'prova'),
  ('UNILUS', 'Santos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMAR', 'Marília', 'SP', 'Sudeste', 'Privada', false, false, false, ''),
  ('UniMax', 'Indaiatuba', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNIME', 'Lauro de Freitas', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMES', 'Santos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMONTES', 'Montes Claros', 'MG', 'Sudeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UNINASSAU', 'Vilhena', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Documental'),
  ('UNINASSAU', 'Recife', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINGÁ', 'Maringá', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINILTONLINS', 'Manaus', 'AM', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINOVAFAPI', 'Teresina', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Guarulhos', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Mauá', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Osasco', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'São Bernardo do Campo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIOESTE', 'Cascavel', 'PR', 'Sul', 'Pública', true, false, false, 'ENEM'),
  ('UNIOESTE', 'Francisco Beltrão', 'PR', 'Sul', 'Pública', true, false, false, 'ENEM'),
  ('UNIP', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPAC', 'Juiz De Fora', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPAM', 'Patos', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIPAMPA', 'Uruguaiana', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIPAR', 'Umuarama', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPÊ', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPLAC', 'Lages', 'SC', 'Sul', 'Privada', false, false, false, ''),
  ('UNIPTAN', 'São João Del Rey', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIR', 'Vilhena', 'RO', 'Norte', 'Pública', false, false, false, 'Enem'),
  ('UniRedentor', 'Itaperuna', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIRG', 'Gurupi', 'TO', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UNIRIO', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UniRV', 'Aparecida De Goiania', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UniRV', 'Rio Verde', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UniRV', 'Goianésia', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNISA', 'Santo Amaro', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNISALESIANO', 'Araçatuba', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNISC', 'Santa Cruz do Sul', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNISINOS', 'São Leopoldo', 'Rio Grande Do Sul', 'Sul', 'Privada', true, false, false, 'ENEM'),
  ('UNISUL', 'Tubarão', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNISUL', 'Pedra Branca', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNIT', 'Aracaju', 'SE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIT', 'Jaboatão Dos Guararapes', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIT', 'Maceió', 'AL', 'Nordeste', 'Privada', false, false, false, 'Prova/Análise'),
  ('UNITAU', 'Taubaté', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNITPAC', 'Araguaína', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('UNIUBE', 'Uberaba', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVAÇO', 'Ipatinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular');