INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('Humanitas', 'São Jose dos Campos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Humanitas', 'São José dos Campos', 'SP', 'Sudesde', 'Privada', false, false, false, 'Prova'),
  ('IMED', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Enem'),
  ('IMEPAC', 'Itumbiara', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('IMEPAC', 'Araguari', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('IMES', 'Ipatinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('INTA-UNINTA', 'Sobral', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('INTA-UNINTA', 'Itapipoca', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Palmas', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Porto Nacional', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Cruzeiro Do Sul', 'AC', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('ITPAC', 'Santa Inês', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('LIFE UNIC', 'Joinville', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('MULTIVIX', 'Vitória', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS BACABAL', 'Babacal', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS CODÓ', 'Codó', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS EUNÁPOLIS', 'Eunápolis', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PUC', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PUC', 'Sorocaba', 'SP', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('PUC', 'Contagem', 'MG', 'Sudeste', 'Privada', true, false, false, 'Enem'),
  ('PUC', 'Betim', 'MG', 'Sudeste', 'Privada', false, false, false, 'Enem'),
  ('PUC', 'Poços de Caldas', 'MG', 'Sudeste', 'Privada', true, false, false, 'Enem'),
  ('PUC', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular/Enem'),
  ('PUC', 'Goiânia', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'ENEM'),
  ('PUC', 'Londrina', 'PR', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('PUC', 'Curitiba', 'PR', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('SAO CAMILO', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UAM', 'São Paulo', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UAM', 'Piracicaba', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UAM', 'São José dos Campos', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UB', 'Fernandópolis', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UCB', 'Taguatinga', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UCPEL', 'Pelotas', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UCS', 'Caxias do Sul', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Vestibular'),
  ('UEA', 'Manaus', 'AM', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UECE', 'Fortaleza', 'CE', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UEFS', 'Feira de Santana', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UEG', 'Itumbiara', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UEL', 'Londrina', 'PR', 'Sul', 'Pública', false, false, false, 'Vestibular'),
  ('UEM', 'Maringá', 'PR', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UEMA', 'Caxias', 'MA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UEMG', 'Passos', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UEMS', 'Dourados', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', true, false, false, 'Prova'),
  ('UEPA', 'Belem', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPA', 'Santarém', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPA/Marabá', 'Marabá', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPG', 'Ponta Grossa', 'PR', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UERJ', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UERN', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UERR', 'Caracaraí', 'RR', 'Norte', 'Pública', false, false, false, 'Prova');