-- Inserção de todas as 383 faculdades

INSERT INTO faculdades (name, cidade, state, regiao, type, aceita_estrangeiro, aceita_fies, obtem_novo_titulo, entrance_method)
VALUES
  ('AFYA PARAÍBA', 'Cabedelo', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('IDEA MEDICINA', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNILAGOS', 'Araruama', 'RJ', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('AESGA', 'Garanhuns', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('AFYA SÃO LUCAS', 'Porto Velho', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('AGES', 'Irecê', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise'),
  ('AGES', 'Jacobina', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise'),
  ('ASCES-UNITA', 'Caruaru', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('Atenas', 'Passos', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Atenas', 'Paracatu', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('Atenas', 'Sete Lagoas', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('CAMPOREAL', 'Guarapuava', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('CEI', 'Campo Mourão', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('CESMAC', 'Maceió', 'AL', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('CESUPA', 'Belém', 'PA', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('CET', 'Teresina', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('CEUB', 'Brasília', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('CEUCLAR', 'Rio Claro', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('EBMSP', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Vestibular'),
  ('EDUFOR', 'São Luis', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('EMESCAM', 'Vitória', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('EMSM', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('ENIAC', 'Guarulhos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('ESCS', 'Brasília', 'DF', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('Estácio', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Alagoinhas', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Canindé', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Juazeiro', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Juazeiro do Norte', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Quixadá', 'CE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Cittá', 'Rio De Janeiro', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Jaraguá Do Sul', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Presidente Vargas', 'Rio De Janeiro', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Castanhal', 'PA', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Cáceres', 'MT', 'Centro-Oeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Teresina', 'PI', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('Estácio', 'Açailandia', 'MA', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAB/UNINORTE', 'Rio Branco', 'AC', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACENE', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACERES', 'São José do Rio Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FACI', '-', 'ES', 'Sudeste', 'Privada', false, false, false, ''),
  ('FACIMED', 'Cacoal', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FACIMPA', 'Marabá', 'PA', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('FACISB', 'Barretos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FADIP', 'Ponte Nova', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAE', 'São João Da Boa Vista', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAG', 'Cascavel', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FAGOC', 'Ubá', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAHESP/iESVAP', 'Parnaíba', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAI', 'Adamantina', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('FAM', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Enem'),
  ('FAME', 'Barbacena', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMEJIPA', 'Ji-Paraná', 'RO', 'Oeste', 'Privada', true, false, false, 'Prova'),
  ('FAMEMA', 'Marília', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('FAMENE', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMERP', 'São Jose do Rio Preto', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('FAMESC', 'Bom Jesus do Itabapoana', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMETRO', 'Manaus', 'AM', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('FAMEU', 'Uberlândia', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAMINAS', 'Muriaé', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMINAS', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FAMP', 'Mineiros', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FAP', 'Araripina', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FAS', 'Lauro De Freitas', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FASA', 'Vitória Da Conquista', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASA', 'Itabuna', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASB', 'Barreiras', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FASEH', 'Vespasiano', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FASM', 'Muriaé', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMMG', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMPB', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FCMS', 'Juiz De Fora', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMSCSP', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FCMTR', 'Três Rios', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FEEVALE', 'Novo Hamburgo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular/Enem'),
  ('FEMA', 'Assis', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FEPAR', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FESAR', 'Redenção', 'PA', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FICSAE', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FIMCA', 'Porto Velho', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('FIP', 'Patos', 'PB', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FIP', 'Montes Claros', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FIP', 'Guanambi', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('FMABC', 'Santo André', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FMC', 'Campos dos Goytacazes', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMIT', 'Itajubá', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMJ', 'Jundiaí', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FMO', 'Olinda', 'PE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('FMP', 'Petrópolis', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FMPFM', 'Mogi Guaçu', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('FPP', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FPS', 'Recife', 'PE', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('FSLM', 'Araras', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FSLM', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('FSM', 'Cajazeiras', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FUNEPE', 'Penápolis', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('FUNORTE', 'Montes Claros', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('FURB', 'Blumenau', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('FURG', 'Rio Grande', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Prova'),
  ('HONPAR', 'Arapongas', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('Humanitas', 'São Jose dos Campos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Humanitas', 'São José dos Campos', 'SP', 'Sudesde', 'Privada', false, false, false, 'Prova'),
  ('IMED', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Enem'),
  ('IMEPAC', 'Itumbiara', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('IMEPAC', 'Araguari', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('IMES', 'Ipatinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('INTA-UNINTA', 'Sobral', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('INTA-UNINTA', 'Itapipoca', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Palmas', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Porto Nacional', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('ITPAC', 'Cruzeiro Do Sul', 'AC', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('ITPAC', 'Santa Inês', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('LIFE UNIC', 'Joinville', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('MULTIVIX', 'Vitória', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS BACABAL', 'Babacal', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS CODÓ', 'Codó', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PITÁGORAS EUNÁPOLIS', 'Eunápolis', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PUC', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('PUC', 'Sorocaba', 'SP', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('PUC', 'Contagem', 'MG', 'Sudeste', 'Privada', true, false, false, 'Enem'),
  ('PUC', 'Betim', 'MG', 'Sudeste', 'Privada', false, false, false, 'Enem'),
  ('PUC', 'Poços de Caldas', 'MG', 'Sudeste', 'Privada', true, false, false, 'Enem'),
  ('PUC', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular/Enem'),
  ('PUC', 'Goiânia', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'ENEM'),
  ('PUC', 'Londrina', 'PR', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('PUC', 'Curitiba', 'PR', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('SAO CAMILO', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UAM', 'São Paulo', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UAM', 'Piracicaba', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UAM', 'São José dos Campos', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UB', 'Fernandópolis', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UCB', 'Taguatinga', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UCPEL', 'Pelotas', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UCS', 'Caxias do Sul', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Vestibular'),
  ('UEA', 'Manaus', 'AM', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UECE', 'Fortaleza', 'CE', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UEFS', 'Feira de Santana', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UEG', 'Itumbiara', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UEL', 'Londrina', 'PR', 'Sul', 'Pública', false, false, false, 'Vestibular'),
  ('UEM', 'Maringá', 'PR', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UEMA', 'Caxias', 'MA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UEMG', 'Passos', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UEMS', 'Dourados', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', true, false, false, 'Prova'),
  ('UEPA', 'Belem', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPA', 'Santarém', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPA/Marabá', 'Marabá', 'PA', 'Norte', 'Pública', false, false, false, 'Transferência'),
  ('UEPG', 'Ponta Grossa', 'PR', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UERJ', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UERN', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UERR', 'Caracaraí', 'RR', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UESB', 'Jequié', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UESB', 'Vitória Da Conquista', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UESC', 'Ilheus', 'BA', 'Nordeste', 'Pública', true, false, false, 'Enem'),
  ('UESPI', 'Teresina', 'PI', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UFAC', 'Rio Branco', 'AC', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFAL', 'Maceió', 'AL', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFAL', 'Arapiraca', 'AL', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFAM', 'Coari', 'AM', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFAM', 'Manaus', 'AM', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFBA', 'Salvador', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova/Análise'),
  ('UFBA', 'Vitória da Conquista', 'BA', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFBM', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UFC', 'Fortaleza', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFC', 'Sobral', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCA', 'Barbalha', 'CE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCAT', 'Goiânia', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFCG', 'Cajazeiras', 'PB', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCG', 'Campina Grande', 'PB', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFCSPA', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UFERSA', 'Mossoro', 'Rio Grande Do Norte', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFES', 'Vitória', 'ES', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFF', 'Niteroi', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UFFS', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UFFS', 'Chapecó', 'SC', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UFG', 'Goiânia', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFG', 'Jataí', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFGD', 'Itahum', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UFJ', 'Riachuelo', 'GO', 'Centro-Oeste', 'Pública', true, false, false, 'Enem'),
  ('UFJF', 'Governador Valares', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFJF', 'Juiz De Fora', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFLA', 'Lavras', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'Pinheiro', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'Imperatriz', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMA', 'São Luís', 'MA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFMG', 'Belo Horizonte', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFMS', 'Campo Grande', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UFMS', 'Três Lagoas', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UFMT', 'Cuiabá', 'MT', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFMT', 'Sinop', 'MT', 'Centro-Oeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFOB', 'Barreiras', 'BA', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFOP', 'Ouro Preto', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFPA', 'Belém', 'PA', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UFPB', 'João Pessoa', 'PB', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFPE', 'Recife', 'PE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPE', 'Caruaru', 'PE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPel', 'Pelotas', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'ENEM'),
  ('UFPI', 'Parnaíba', 'PI', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UFPI', 'Teresina', 'PI', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPI', 'Picos', 'PI', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFPR', 'Toledo', 'PR', 'Sul', 'Pública', true, false, false, 'Prova'),
  ('UFPR', 'Curitiba', 'PR', 'Sul', 'Pública', true, false, false, 'Prova'),
  ('UFR', 'Rondonópolis', 'MT', 'Centro-Oeste', 'Pública', false, false, false, ''),
  ('UFRB', 'Santo Antônio de Jesus', 'BA', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFRGS', 'Porto Alegre', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFRJ', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFRJ', 'Macaé', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFRN', 'Natal', 'Rio Grande Do Norte', 'Nordeste', 'Pública', true, false, false, 'Enem'),
  ('UFRN', 'Caicó', 'Rio Grande Do Norte', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFRR', 'Boa Vista', 'RR', 'Norte', 'Pública', true, false, false, 'Enem'),
  ('UFS', 'Lagarto', 'SE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFS', 'São Cristóvão', 'SE', 'Nordeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UFSBA', 'Teixeira De Freitas', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UFSC', 'Araranguá', 'SC', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFSC', 'Florianópolis', 'SC', 'Sul', 'Pública', true, false, false, 'Análise Curricular'),
  ('UFSCAR', 'São Carlos', 'SP', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFSJ', 'São João Del Rey', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFSJ', 'Divinópolis', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFSM', 'Santa Maria', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UFT', 'Palmas', 'TO', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UFT', 'Araguaína', 'TO', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UFTM', 'Uberaba', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFU', 'Uberlândia', 'MG', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('UFV', 'Viçosa', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UFVJM', 'Diamantina', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFVJM', 'Teófilo Otoni', 'MG', 'Sudeste', 'Pública', true, false, false, 'Enem'),
  ('UFVSF', 'Paulo Afonso', 'BA', 'Nordeste', 'Pública', false, false, false, 'Prova'),
  ('UIt', 'Itaúna', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('ULBRA', 'Canoas', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UMC', 'Mogi das Cruzes', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNA', 'Tucurí', 'PA', 'Norte', 'Privada', true, false, false, 'Prova'),
  ('UNAERP', 'Ribeirão Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UnB', 'Brasília', 'DF', 'Centro-Oeste', 'Pública', false, false, false, 'Enem'),
  ('UnC', 'Mafra', 'SC', 'Sul', 'Privada', true, false, false, 'Análise Curricular'),
  ('UNCISAL', 'Maceió', 'AL', 'Nordeste', 'Pública', false, false, false, 'ENEM'),
  ('UNDB', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNEB', 'Salvador', 'BA', 'Nordeste', 'Pública', true, false, false, 'Enem e Análise Curricular'),
  ('Unec', 'Caratinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNECEPLAC', 'Brasilia', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Enem'),
  ('UNEMAT', 'Caceres', 'MT', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNESC', 'Criciúma', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNESC', 'Colatina', 'ES', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNESP', 'Botucatu', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('UNESUL', 'Eunápolis', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNEX', 'Vitória da Conquista', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova/Análise Curricular'),
  ('UNI-BH', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNI-FACEF', 'Franca', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UNIARA', 'Araraquara', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIARP', 'Caçador', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNIC', 'Cuiabá', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNICAMP', 'Campinas', 'SP', 'Sudeste', 'Pública', true, false, false, 'Prova'),
  ('UNICAP', 'Recife', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICENTRO', 'Guarapuava', 'PR', 'Sul', 'Pública', false, false, false, 'Enem'),
  ('UNICEPLAC', 'Brasília', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNICERRADO', 'Goiatuba', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNICESUMAR', 'Maringá', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNICESUMAR', 'Corumbá', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Privada', true, false, false, 'Análise Curricular'),
  ('UNICEUB', 'Brasilia', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNICEUMA', 'São Luís', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICEUMA', 'Imperatriz', 'MA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICHRISTUS', 'Fortaleza', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNICID', 'São Paulo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('Unidavi', 'Rio do Sul', 'SC', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIDEP', 'Pato Branco', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIDERP', 'Campo Grande', 'Mato Grosso Do Sul', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIDOMPEDRO', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIEURO', 'Taguatinga', 'DF', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UniEVANGELICA', 'Anápolis', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAA', 'Valença', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFACCAMP', 'Campo Limpo Paulista', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova/Análise Curricular'),
  ('UNIFACEMP', 'Santo Antônio de Jesus', 'BA', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFACIG', 'Manhuaçu', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFACISA', 'Campina Grande', 'PB', 'Nordeste', 'Privada', false, false, false, 'Enem'),
  ('UNIFACS', 'Salvador', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFADRA', 'Dracena', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAESF', 'Floriano', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFAJ', 'Jaguariúna', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFAL', 'Alfenas', 'MG', 'Sudeste', 'Pública', false, false, false, 'Enem e Análise Curricular'),
  ('UNIFAMAZ', 'Belém', 'PA', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFAN', 'Aparecida De Goiania', 'GO', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFAP', 'Macapá', 'AP', 'Norte', 'Pública', false, false, false, 'Prova'),
  ('UNIFEBE', 'Brusque', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIFEBE', 'Brusque', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIFENAS', 'Alfenas', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFENAS-BH', 'Belo Horizonte', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFESO', 'Teresópolis', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIFESP', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UNIFEV', 'Votuporanga', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFG', 'Guanambi', 'BA', 'Nordeste', 'Privada', true, false, false, 'Prova'),
  ('UNIFIMES', 'Mineiros', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIFIMES', 'Trindade', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIFIPA', 'Catanduva', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFOA', 'Volta Redonda', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFOR', 'Fortaleza', 'CE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFRA', 'Santa Maria', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Vestibular'),
  ('UNIFRAN', 'Franca', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UniFTC', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIFUNEC', 'Santa Fé do Sul', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIG', 'Itaperuna', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIG', 'Nova Iguaçu', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIGRANRIO', 'Duque De Caxias', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIGRANRIO', 'Barra da Tijuca', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIJUI', 'Ijuí', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Enem'),
  ('UNILA', 'Foz do Iguaçu', 'PR', 'Sul', 'Pública', true, false, false, 'Enem'),
  ('UNILAGO', 'São Jose do Rio Preto', 'SP', 'Sudeste', 'Privada', false, false, false, 'prova'),
  ('UNILUS', 'Santos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMAR', 'Marília', 'SP', 'Sudeste', 'Privada', false, false, false, ''),
  ('UniMax', 'Indaiatuba', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNIME', 'Lauro de Freitas', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMES', 'Santos', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIMONTES', 'Montes Claros', 'MG', 'Sudeste', 'Pública', true, false, false, 'Análise Curricular'),
  ('UNINASSAU', 'Vilhena', 'RO', 'Norte', 'Privada', false, false, false, 'Análise Documental'),
  ('UNINASSAU', 'Recife', 'PE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINGÁ', 'Maringá', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINILTONLINS', 'Manaus', 'AM', 'Norte', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINOVAFAPI', 'Teresina', 'PI', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Guarulhos', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Mauá', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'Osasco', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNINOVE', 'São Bernardo do Campo', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIOESTE', 'Cascavel', 'PR', 'Sul', 'Pública', true, false, false, 'ENEM'),
  ('UNIOESTE', 'Francisco Beltrão', 'PR', 'Sul', 'Pública', true, false, false, 'ENEM'),
  ('UNIP', 'Campinas', 'SP', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPAC', 'Juiz De Fora', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPAM', 'Patos', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIPAMPA', 'Uruguaiana', 'Rio Grande Do Sul', 'Sul', 'Pública', false, false, false, 'Análise Curricular'),
  ('UNIPAR', 'Umuarama', 'PR', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPÊ', 'João Pessoa', 'PB', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIPLAC', 'Lages', 'SC', 'Sul', 'Privada', false, false, false, ''),
  ('UNIPTAN', 'São João Del Rey', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIR', 'Vilhena', 'RO', 'Norte', 'Pública', false, false, false, 'Enem'),
  ('UniRedentor', 'Itaperuna', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIRG', 'Gurupi', 'TO', 'Norte', 'Pública', true, false, false, 'Prova'),
  ('UNIRIO', 'Rio De Janeiro', 'Rio De Janeiro', 'Sudeste', 'Pública', false, false, false, 'Enem'),
  ('UniRV', 'Aparecida De Goiania', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UniRV', 'Rio Verde', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UniRV', 'Goianésia', 'GO', 'Centro-Oeste', 'Pública', false, false, false, 'Prova'),
  ('UNISA', 'Santo Amaro', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNISALESIANO', 'Araçatuba', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNISC', 'Santa Cruz do Sul', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNISINOS', 'São Leopoldo', 'Rio Grande Do Sul', 'Sul', 'Privada', true, false, false, 'ENEM'),
  ('UNISUL', 'Tubarão', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNISUL', 'Pedra Branca', 'SC', 'Sul', 'Privada', true, false, false, 'Prova'),
  ('UNIT', 'Aracaju', 'SE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIT', 'Jaboatão Dos Guararapes', 'PE', 'Nordeste', 'Privada', false, false, false, 'Prova'),
  ('UNIT', 'Maceió', 'AL', 'Nordeste', 'Privada', false, false, false, 'Prova/Análise'),
  ('UNITAU', 'Taubaté', 'SP', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNITPAC', 'Araguaína', 'TO', 'Norte', 'Privada', false, false, false, 'Prova'),
  ('UNIUBE', 'Uberaba', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVAÇO', 'Ipatinga', 'MG', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIVAG', 'Várzea Grande', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNIVALE MG', 'Governador Valares', 'MG', 'Sudeste', 'Privada', false, false, false, 'ENEM'),
  ('UNIVALI', 'Itajaí', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNIVAR', 'Barra dos Garças', 'MT', 'Centro-Oeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVAS', 'Pouso Alegre', 'MG', 'Sudeste', 'Privada', false, false, false, 'Prova'),
  ('UNIVASF', 'Petrolina', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UNIVASF', 'Petrolina', 'BA', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UNIVATES', 'Lajeado', 'Rio Grande Do Sul', 'Sul', 'Privada', true, false, false, 'ENEM'),
  ('Universidade de Vassouras', 'Vassouras', 'Rio De Janeiro', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('Univértix', 'Matipó', 'MG', 'Sudeste', 'Privada', false, false, false, 'Vestibular'),
  ('UNIVILLE', 'Joinville', 'SC', 'Sul', 'Privada', false, false, false, 'Análise'),
  ('UNIVS', 'Icó', 'CE', 'Nordeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UNOCHAPECO', 'Chapecó', 'SC', 'Sul', 'Pública', false, false, false, 'Prova'),
  ('UNOESC', 'Joaçaba', 'SC', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UNOESTE', 'Guarujá', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UNOESTE', 'Presidente Prudente', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('UnP', 'Natal', 'Rio Grande Do Norte', 'Nordeste', 'Privada', true, false, false, 'Análise Curricular'),
  ('UP', 'Curitiba', 'PR', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('UPE', 'Garanhuns', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPE', 'Recife', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPE', 'Serra Talhada', 'PE', 'Nordeste', 'Pública', false, false, false, 'Enem'),
  ('UPF', 'Passo Fundo', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('URI ERECHIM', 'Erechim', 'Rio Grande Do Sul', 'Sul', 'Privada', false, false, false, 'Prova'),
  ('USCS', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USCS', 'São Caetano do Sul', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USF', 'Bragança Paulista', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USJT', 'São Paulo', 'SP', 'Sudeste', 'Privada', true, false, false, 'Prova'),
  ('USP', 'Bauru', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USP', 'Ribeirão Preto', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('USP', 'São Paulo', 'SP', 'Sudeste', 'Pública', false, false, false, 'Prova'),
  ('UVA', 'Rio de Janeiro', 'RJ', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('UVV', 'Vila Velha', 'ES', 'Sudeste', 'Privada', false, false, false, 'Análise Curricular'),
  ('ZARNS', 'Salvador', 'BA', 'Nordeste', 'Privada', false, false, false, 'Prova');
