-- Lote 1 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PB', 'AFYA PARAÍBA', 'Nordeste', 'Paraíba', 'Cabedelo', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'IDEA MEDICINA', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNILAGOS', 'Sudeste', 'Rio de Janeiro', 'Araruama', 'Privada', false, false, 'Análise Curricular', false),
  ('PE', 'AESGA', 'Nordeste', 'Pernambuco', 'Garanhuns', 'Privada', false, false, 'Análise Curricular', false),
  ('RO', 'AFYA SÃO LUCAS', 'Norte', 'Rondônia', 'Porto Velho', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'AGES', 'Nordeste', 'Bahia', 'Irecê', 'Privada', false, true, 'Prova/Análise', false),
  ('BA', 'AGES', 'Nordeste', 'Bahia', 'Jacobina', 'Privada', false, true, 'Prova/Análise', false),
  ('PE', 'ASCES-UNITA', 'Nordeste', 'Pernambuco', 'Caruaru', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Passos', 'Privada', false, false, 'Prova', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Paracatu', 'Privada', false, false, 'Vestibular', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Sete Lagoas', 'Privada', false, false, 'Vestibular', false),
  ('PR', 'CAMPOREAL', 'Sul', 'Paraná', 'Guarapuava', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'CEI', 'Sul', 'Paraná', 'Campo Mourão', 'Privada', false, false, 'Prova', false),
  ('AL', 'CESMAC', 'Nordeste', 'Alagoas', 'Maceió', 'Privada', false, false, 'Prova', false),
  ('PA', 'CESUPA', 'Norte', 'Pará', 'Belém', 'Privada', false, false, 'Prova', false),
  ('PI', 'CET', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, false, 'Análise Curricular', false),
  ('DF', 'CEUB', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Privada', false, false, 'Prova', false),
  ('SP', 'CEUCLAR', 'Sudeste', 'São Paulo', 'Rio Claro', 'Privada', false, false, 'Prova', false),
  ('BA', 'EBMSP', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Vestibular', false),
  ('MA', 'EDUFOR', 'Nordeste', 'Maranhão', 'São Luis', 'Privada', false, false, 'Prova', false),
  ('ES', 'EMESCAM', 'Sudeste', 'Espírito Santo', 'Vitória', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'EMSM', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'ENIAC', 'Sudeste', 'São Paulo', 'Guarulhos', 'Privada', false, false, 'Prova', false),
  ('DF', 'ESCS', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Pública', false, false, 'Prova', false),
  ('SP', 'Estácio', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, true, 'Prova', false),
  ('BA', 'Estácio', 'Nordeste', 'Bahia', 'Alagoinhas', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Canindé', 'Privada', false, true, 'Prova', false),
  ('BA', 'Estácio', 'Nordeste', 'Bahia', 'Juazeiro', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Juazeiro do Norte', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Quixadá', 'Privada', false, true, 'Prova', false),
  ('RJ', 'Estácio', 'Sudeste', 'Rio De Janeiro', 'Cittá', 'Privada', false, true, 'Prova', false),
  ('SC', 'Estácio', 'Sul', 'Santa Catarina', 'Jaraguá Do Sul', 'Privada', false, true, 'Prova', false),
  ('RJ', 'Estácio', 'Sudeste', 'Rio De Janeiro', 'Presidente Vargas', 'Privada', false, true, 'Prova', false),
  ('PA', 'Estácio', 'Norte', 'Pará', 'Castanhal', 'Privada', false, true, 'Prova', false),
  ('MT', 'Estácio', 'Centro-Oeste', 'Mato Grosso', 'Cáceres', 'Privada', false, true, 'Prova', false),
  ('PI', 'Estácio', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, true, 'Prova', false),
  ('MA', 'Estácio', 'Sudeste', 'Maranhão', 'Açailandia', 'Privada', false, false, 'Prova', false),
  ('AC', 'FAB/UNINORTE', 'Norte', 'Acre', 'Rio Branco', 'Privada', false, false, 'Análise Curricular', false),
  ('RN', 'FACENE', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FACERES', 'Sudeste', 'São Paulo', 'São José do Rio Preto', 'Privada', false, false, 'Prova', false),
  ('ES', 'FACI', 'Sudeste', 'Espírito Santo', '-', 'Privada', false, false, 'Não informado', false),
  ('RO', 'FACIMED', 'Norte', 'Rondônia', 'Cacoal', 'Privada', false, false, 'Análise Curricular', false),
  ('PA', 'FACIMPA', 'Norte', 'Pará', 'Marabá', 'Privada', false, false, 'Prova', false),
  ('SP', 'FACISB', 'Sudeste', 'São Paulo', 'Barretos', 'Privada', false, false, 'Prova', false),
  ('MG', 'FADIP', 'Sudeste', 'Minas Gerais', 'Ponte Nova', 'Privada', false, false, 'Prova', false),
  ('SP', 'FAE', 'Sudeste', 'São Paulo', 'São João Da Boa Vista', 'Privada', false, false, 'Prova', false),
  ('PR', 'FAG', 'Sul', 'Paraná', 'Cascavel', 'Privada', false, false, 'Prova', false),
  ('MG', 'FAGOC', 'Sudeste', 'Minas Gerais', 'Ubá', 'Privada', false, false, 'Prova', false),
  ('PI', 'FAHESP/iESVAP', 'Nordeste', 'Piauí', 'Parnaíba', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FAI', 'Sudeste', 'São Paulo', 'Adamantina', 'Pública', false, false, 'Prova', false);

-- Lote 2 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('SP', 'FAM', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Enem', false),
  ('MG', 'FAME', 'Sudeste', 'Minas Gerais', 'Barbacena', 'Privada', false, false, 'Prova', false),
  ('RO', 'FAMEJIPA', 'Oeste', 'Rondônia', 'Ji-Paraná', 'Privada', false, true, 'Prova', false),
  ('SP', 'FAMEMA', 'Sudeste', 'São Paulo', 'Marília', 'Publica', false, false, 'Prova', false),
  ('PB', 'FAMENE', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FAMERP', 'Sudeste', 'São Paulo', 'São Jose do Rio Preto', 'Pública', false, true, 'Prova', false),
  ('RJ', 'FAMESC', 'Sudeste', 'Rio De Janeiro', 'Bom Jesus do Itabapoana', 'Privada', false, false, 'Análise Curricular', false),
  ('AM', 'FAMETRO', 'Norte', 'Amazonas', 'Manaus', 'Privada', false, true, 'Prova', false),
  ('MG', 'FAMEU', 'Sudeste', 'Minas Gerais', 'Uberlândia', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FAMINAS', 'Sudeste', 'Minas Gerais', 'Muriaé', 'Privada', false, false, 'Prova', false),
  ('MG', 'FAMINAS', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Prova', false),
  ('GO', 'FAMP', 'Centro-Oeste', 'Goiás', 'Mineiros', 'Privada', false, false, 'Análise Curricular', false),
  ('PE', 'FAP', 'Nordeste', 'Pernambuco', 'Araripina', 'Privada', false, false, 'Prova', false),
  ('BA', 'FAS', 'Nordeste', 'Bahia', 'Lauro De Freitas', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'FASA', 'Nordeste', 'Bahia', 'Vitória Da Conquista', 'Privada', false, false, 'Prova', false),
  ('BA', 'FASA', 'Nordeste', 'Bahia', 'Itabuna', 'Privada', false, false, 'Prova', false),
  ('BA', 'FASB', 'Nordeste', 'Bahia', 'Barreiras', 'Privada', false, false, 'Prova', false),
  ('MG', 'FASEH', 'Sudeste', 'Minas Gerais', 'Vespasiano', 'Privada', false, true, 'Prova', false),
  ('SP', 'FASM', 'Sudeste', 'São Paulo', 'Muriaé', 'Privada', false, false, 'Prova', false),
  ('MG', 'FCMMG', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Prova', false),
  ('PB', 'FCMPB', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FCMS', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Privada', false, false, 'Prova', false),
  ('SP', 'FCMSCSP', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('RJ', 'FCMTR', 'Sudeste', 'Rio De Janeiro', 'Três Rios', 'Privada', false, false, 'Prova', false),
  ('RS', 'FEEVALE', 'Sul', 'Rio Grande Do Sul', 'Novo Hamburgo', 'Privada', false, false, 'Análise Curricular/Enem', false),
  ('SP', 'FEMA', 'Sudeste', 'São Paulo', 'Assis', 'Privada', false, false, 'Prova', false),
  ('PR', 'FEPAR', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PA', 'FESAR', 'Norte', 'Pará', 'Redenção', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FICSAE', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('RO', 'FIMCA', 'Norte', 'Rondônia', 'Porto Velho', 'Privada', false, false, 'Análise Curricular', false),
  ('PB', 'FIP', 'Nordeste', 'Paraíba', 'Patos', 'Privada', false, false, 'Prova', false),
  ('MG', 'FIP', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Privada', false, false, 'Prova', false),
  ('BA', 'FIP', 'Nordeste', 'Bahia', 'Guanambi', 'Privada', false, false, 'Prova', false),
  ('SP', 'FMABC', 'Sudeste', 'São Paulo', 'Santo André', 'Privada', false, true, 'Prova', false),
  ('RJ', 'FMC', 'Sudeste', 'Rio De Janeiro', 'Campos dos Goytacazes', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FMIT', 'Sudeste', 'Minas Gerais', 'Itajubá', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FMJ', 'Sudeste', 'São Paulo', 'Jundiaí', 'Privada', false, false, 'Prova', false),
  ('PE', 'FMO', 'Nordeste', 'Pernambuco', 'Olinda', 'Privada', false, true, 'Prova', false),
  ('RJ', 'FMP', 'Sudeste', 'Rio De Janeiro', 'Petrópolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FMPFM', 'Sudeste', 'São Paulo', 'Mogi Guaçu', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'FPP', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PE', 'FPS', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, true, 'Prova', false),
  ('SP', 'FSLM', 'Sudeste', 'São Paulo', 'Araras', 'Privada', false, false, 'Prova', false),
  ('SP', 'FSLM', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Prova', false),
  ('PB', 'FSM', 'Nordeste', 'Paraíba', 'Cajazeiras', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FUNEPE', 'Sudeste', 'São Paulo', 'Penápolis', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FUNORTE', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Privada', false, true, 'Prova', false),
  ('SC', 'FURB', 'Sul', 'Santa Catarina', 'Blumenau', 'Privada', false, false, 'Prova', false),
  ('RS', 'FURG', 'Sul', 'Rio Grande Do Sul', 'Rio Grande', 'Pública', false, false, 'Prova', false),
  ('PR', 'HONPAR', 'Sul', 'Paraná', 'Arapongas', 'Privada', false, false, 'Análise Curricular', false);

-- Lote 3 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('SP', 'Humanitas', 'Sudeste', 'São Paulo', 'São Jose dos Campos', 'Privada', false, false, 'Prova', false),
  ('SP', 'Humanitas', 'Sudesde', 'São Paulo', 'São José dos Campos', 'Privada', false, false, 'Prova', false),
  ('RS', 'IMED', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Privada', false, false, 'Enem', false),
  ('GO', 'IMEPAC', 'Centro-Oeste', 'Goiás', 'Itumbiara', 'Privada', false, false, 'Prova', false),
  ('MG', 'IMEPAC', 'Sudeste', 'Minas Gerais', 'Araguari', 'Privada', false, false, 'Prova', false),
  ('MG', 'IMES', 'Sudeste', 'Minas Gerais', 'Ipatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('CE', 'INTA-UNINTA', 'Nordeste', 'Ceará', 'Sobral', 'Privada', false, false, 'Prova', false),
  ('CE', 'INTA-UNINTA', 'Nordeste', 'Ceará', 'Itapipoca', 'Privada', false, false, 'Prova', false),
  ('TO', 'ITPAC', 'Norte', 'Tocantins', 'Palmas', 'Privada', false, false, 'Prova', false),
  ('TO', 'ITPAC', 'Norte', 'Tocantins', 'Porto Nacional', 'Privada', false, false, 'Prova', false),
  ('AC', 'ITPAC', 'Norte', 'Acre', 'Cruzeiro Do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'ITPAC', 'Nordeste', 'Maranhão', 'Santa Inês', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'LIFE UNIC', 'Sul', 'Santa Catarina', 'Joinville', 'Privada', false, false, 'Prova', false),
  ('ES', 'MULTIVIX', 'Sudeste', 'Espírito Santo', 'Vitória', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'PITÁGORAS BACABAL', 'Nordeste', 'Maranhão', 'Babacal', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'PITÁGORAS CODÓ', 'Nordeste', 'Maranhão', 'Codó', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'PITÁGORAS EUNÁPOLIS', 'Nordeste', 'Bahia', 'Eunápolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'PUC', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'PUC', 'Sudeste', 'São Paulo', 'Sorocaba', 'Privada', false, false, 'Vestibular', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Contagem', 'Privada', false, true, 'Enem', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Betim', 'Privada', false, false, 'Enem', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Poços de Caldas', 'Privada', false, true, 'Enem', false),
  ('RS', 'PUC', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Privada', false, false, 'Análise Curricular/Enem', false),
  ('GO', 'PUC', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Privada', false, false, 'ENEM', false),
  ('PR', 'PUC', 'Sul', 'Paraná', 'Londrina', 'Privada', false, true, 'Prova', false),
  ('PR', 'PUC', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, true, 'Prova', false),
  ('SP', 'SAO CAMILO', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, true, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'Piracicaba', 'Privada', false, true, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'São José dos Campos', 'Privada', false, true, 'Prova', false),
  ('SP', 'UB', 'Sudeste', 'São Paulo', 'Fernandópolis', 'Privada', false, true, 'Prova', false),
  ('DF', 'UCB', 'Centro-Oeste', 'Distrito Federal', 'Taguatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UCPEL', 'Sul', 'Rio Grande Do Sul', 'Pelotas', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UCS', 'Sul', 'Rio Grande Do Sul', 'Caxias do Sul', 'Privada', false, false, 'Vestibular', false),
  ('AM', 'UEA', 'Norte', 'Amazonas', 'Manaus', 'Pública', false, false, 'Prova', false),
  ('CE', 'UECE', 'Nordeste', 'Ceará', 'Fortaleza', 'Pública', false, false, 'Prova', false),
  ('BA', 'UEFS', 'Nordeste', 'Bahia', 'Feira de Santana', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('GO', 'UEG', 'Centro-Oeste', 'Goiás', 'Itumbiara', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UEL', 'Sul', 'Paraná', 'Londrina', 'Pública', false, false, 'Vestibular', false),
  ('PR', 'UEM', 'Sul', 'Paraná', 'Maringá', 'Pública', false, true, 'Análise Curricular', false),
  ('MA', 'UEMA', 'Nordeste', 'Maranhão', 'Caxias', 'Pública', false, false, 'Prova', false),
  ('MG', 'UEMG', 'Sudeste', 'Minas Gerais', 'Passos', 'Pública', false, true, 'Enem', false),
  ('MS', 'UEMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Dourados', 'Pública', false, true, 'Prova', false),
  ('PA', 'UEPA', 'Norte', 'Pará', 'Belem', 'Pública', false, false, 'Transferência', false),
  ('PA', 'UEPA', 'Norte', 'Pará', 'Santarém', 'Pública', false, false, 'Transferência', false),
  ('PA', 'UEPA/Marabá', 'Norte', 'Pará', 'Marabá', 'Pública', false, false, 'Transferência', false),
  ('PR', 'UEPG', 'Sul', 'Paraná', 'Ponta Grossa', 'Pública', false, false, 'Análise Curricular', false),
  ('RJ', 'UERJ', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Análise Curricular', false),
  ('RN', 'UERN', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Pública', false, true, 'Análise Curricular', false),
  ('RR', 'UERR', 'Norte', 'Roraima', 'Caracaraí', 'Pública', false, false, 'Prova', false);

-- Lote 4 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('BA', 'UESB', 'Nordeste', 'Bahia', 'Jequié', 'Pública', false, false, 'Prova', false),
  ('BA', 'UESB', 'Nordeste', 'Bahia', 'Vitória Da Conquista', 'Pública', false, false, 'Prova', false),
  ('BA', 'UESC', 'Nordeste', 'Bahia', 'Ilheus', 'Pública', false, true, 'Enem', false),
  ('PI', 'UESPI', 'Nordeste', 'Piauí', 'Teresina', 'Pública', false, false, 'Prova', false),
  ('AC', 'UFAC', 'Norte', 'Acre', 'Rio Branco', 'Pública', false, true, 'Prova', false),
  ('AL', 'UFAL', 'Nordeste', 'Alagoas', 'Maceió', 'Pública', false, false, 'Enem', false),
  ('AL', 'UFAL', 'Nordeste', 'Alagoas', 'Arapiraca', 'Pública', false, false, 'Enem', false),
  ('AM', 'UFAM', 'Norte', 'Amazonas', 'Coari', 'Pública', false, true, 'Prova', false),
  ('AM', 'UFAM', 'Norte', 'Amazonas', 'Manaus', 'Pública', false, true, 'Prova', false),
  ('BA', 'UFBA', 'Nordeste', 'Bahia', 'Salvador', 'Pública', false, false, 'Prova/Análise', false),
  ('BA', 'UFBA', 'Nordeste', 'Bahia', 'Vitória da Conquista', 'Pública', false, false, 'ENEM', false),
  ('SP', 'UFBM', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, true, 'Prova', false),
  ('CE', 'UFC', 'Nordeste', 'Ceará', 'Fortaleza', 'Pública', false, false, 'Enem', false),
  ('CE', 'UFC', 'Nordeste', 'Ceará', 'Sobral', 'Pública', false, false, 'Enem', false),
  ('CE', 'UFCA', 'Nordeste', 'Ceará', 'Barbalha', 'Pública', false, false, 'Enem', false),
  ('GO', 'UFCAT', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Publica', false, true, 'Enem', false),
  ('PB', 'UFCG', 'Nordeste', 'Paraíba', 'Cajazeiras', 'Pública', false, false, 'Enem', false),
  ('PB', 'UFCG', 'Nordeste', 'Paraíba', 'Campina Grande', 'Pública', false, false, 'Enem', false),
  ('RS', 'UFCSPA', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('RN', 'UFERSA', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Pública', false, false, 'Enem', false),
  ('ES', 'UFES', 'Sudeste', 'Espírito Santo', 'Vitória', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UFF', 'Sudeste', 'Rio De Janeiro', 'Niteroi', 'Pública', false, false, 'Prova', false),
  ('RS', 'UFFS', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Pública', false, true, 'Enem', false),
  ('SC', 'UFFS', 'Sul', 'Santa Catarina', 'Chapecó', 'Pública', false, true, 'Enem', false),
  ('GO', 'UFG', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Pública', false, true, 'Enem', false),
  ('GO', 'UFG', 'Centro-Oeste', 'Goiás', 'Jataí', 'Pública', false, true, 'Enem', false),
  ('MS', 'UFGD', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Itahum', 'Pública', false, false, 'Prova', false),
  ('GO', 'UFJ', 'Centro-Oeste', 'Goiás', 'Riachuelo', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFJF', 'Sudeste', 'Minas Gerais', 'Governador Valares', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFJF', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFLA', 'Sudeste', 'Minas Gerais', 'Lavras', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'Pinheiro', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'Imperatriz', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'São Luís', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFMG', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Pública', false, true, 'Enem', false),
  ('MS', 'UFMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Campo Grande', 'Pública', false, false, 'Enem', false),
  ('MS', 'UFMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Três Lagoas', 'Pública', false, false, 'Enem', false),
  ('MT', 'UFMT', 'Centro-Oeste', 'Mato Grosso', 'Cuiabá', 'Pública', false, false, 'Análise Curricular', false),
  ('MT', 'UFMT', 'Centro-Oeste', 'Mato Grosso', 'Sinop', 'Pública', false, true, 'Análise Curricular', false),
  ('BA', 'UFOB', 'Nordeste', 'Bahia', 'Barreiras', 'Pública', false, false, 'Análise Curricular', false),
  ('MG', 'UFOP', 'Sudeste', 'Minas Gerais', 'Ouro Preto', 'Pública', false, false, 'Enem', false),
  ('PA', 'UFPA', 'Norte', 'Pará', 'Belém', 'Pública', false, true, 'Prova', false),
  ('PB', 'UFPB', 'Nordeste', 'Paraíba', 'João Pessoa', 'Pública', false, false, 'ENEM', false),
  ('PE', 'UFPE', 'Nordeste', 'Pernambuco', 'Recife', 'Pública', false, false, 'Análise Curricular', false),
  ('PE', 'UFPE', 'Nordeste', 'Pernambuco', 'Caruaru', 'Pública', false, false, 'Análise Curricular', false),
  ('RS', 'UFPel', 'Sul', 'Rio Grande Do Sul', 'Pelotas', 'Pública', false, false, 'ENEM', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Parnaíba', 'Pública', false, false, 'ENEM', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Teresina', 'Pública', false, false, 'Análise Curricular', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Picos', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UFPR', 'Sul', 'Paraná', 'Toledo', 'Pública', false, true, 'Prova', false);

-- Lote 5 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PR', 'UFPR', 'Sul', 'Paraná', 'Curitiba', 'Pública', false, true, 'Prova', false),
  ('MT', 'UFR', 'Centro-Oeste', 'Mato Grosso', 'Rondonópolis', 'Pública', false, false, 'Não informado', false),
  ('BA', 'UFRB', 'Nordeste', 'Bahia', 'Santo Antônio de Jesus', 'Pública', false, false, 'Análise Curricular', false),
  ('RS', 'UFRGS', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Pública', false, false, 'Análise Curricular', false),
  ('RJ', 'UFRJ', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UFRJ', 'Sudeste', 'Rio De Janeiro', 'Macaé', 'Pública', false, false, 'Enem', false),
  ('RN', 'UFRN', 'Nordeste', 'Rio Grande Do Norte', 'Natal', 'Pública', false, true, 'Enem', false),
  ('RN', 'UFRN', 'Nordeste', 'Rio Grande Do Norte', 'Caicó', 'Pública', false, false, 'Enem', false),
  ('RR', 'UFRR', 'Norte', 'Roraima', 'Boa Vista', 'Pública', false, true, 'Enem', false),
  ('SE', 'UFS', 'Nordeste', 'Sergipe', 'Lagarto', 'Pública', false, false, 'Análise Curricular', false),
  ('SE', 'UFS', 'Nordeste', 'Sergipe', 'São Cristóvão', 'Pública', false, false, 'Análise Curricular', false),
  ('BA', 'UFSBA', 'Nordeste', 'Bahia', 'Teixeira De Freitas', 'Pública', false, false, 'Enem', false),
  ('SC', 'UFSC', 'Sul', 'Santa Catarina', 'Araranguá', 'Pública', false, true, 'Análise Curricular', false),
  ('SC', 'UFSC', 'Sul', 'Santa Catarina', 'Florianópolis', 'Pública', false, true, 'Análise Curricular', false),
  ('SP', 'UFSCAR', 'Sudeste', 'São Paulo', 'São Carlos', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFSJ', 'Sudeste', 'Minas Gerais', 'São João Del Rey', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFSJ', 'Sudeste', 'Minas Gerais', 'Divinópolis', 'Pública', false, true, 'Enem', false),
  ('RS', 'UFSM', 'Sul', 'Rio Grande Do Sul', 'Santa Maria', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('TO', 'UFT', 'Norte', 'Tocantins', 'Palmas', 'Pública', false, false, 'Prova', false),
  ('TO', 'UFT', 'Norte', 'Tocantins', 'Araguaína', 'Pública', false, false, 'Prova', false),
  ('MG', 'UFTM', 'Sudeste', 'Minas Gerais', 'Uberaba', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFU', 'Sudeste', 'Minas Gerais', 'Uberlândia', 'Pública', false, true, 'Prova', false),
  ('MG', 'UFV', 'Sudeste', 'Minas Gerais', 'Viçosa', 'Publica', false, false, 'Enem', false),
  ('MG', 'UFVJM', 'Sudeste', 'Minas Gerais', 'Diamantina', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFVJM', 'Sudeste', 'Minas Gerais', 'Teófilo Otoni', 'Pública', false, true, 'Enem', false),
  ('BA', 'UFVSF', 'Nordeste', 'Bahia', 'Paulo Afonso', 'Pública', false, false, 'Prova', false),
  ('MG', 'UIt', 'Sudeste', 'Minas Gerais', 'Itaúna', 'Privada', false, false, 'Vestibular', false),
  ('RS', 'ULBRA', 'Sul', 'Rio Grande Do Sul', 'Canoas', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UMC', 'Sudeste', 'São Paulo', 'Mogi das Cruzes', 'Privada', false, false, 'Prova', false),
  ('PA', 'UNA', 'Norte', 'Pará', 'Tucurí', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNAERP', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, false, 'Prova', false),
  ('DF', 'UnB', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Publica', false, false, 'Enem', false),
  ('SC', 'UnC', 'Sul', 'Santa Catarina', 'Mafra', 'Privada', false, true, 'Análise Curricular', false),
  ('AL', 'UNCISAL', 'Nordeste', 'Alagoas', 'Maceió', 'Pública', false, false, 'ENEM', false),
  ('MA', 'UNDB', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'UNEB', 'Nordeste', 'Bahia', 'Salvador', 'Pública', false, true, 'Enem e Análise Curricular', false),
  ('MG', 'Unec', 'Sudeste', 'Minas Gerais', 'Caratinga', 'Privada', false, false, 'Prova', false),
  ('DF', 'UNECEPLAC', 'Centro-Oeste', 'Distrito Federal', 'Brasilia', 'Privada', false, false, 'Enem', false),
  ('MT', 'UNEMAT', 'Centro-Oeste', 'Mato Grosso', 'Caceres', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNESC', 'Sul', 'Santa Catarina', 'Criciúma', 'Privada', false, false, 'Prova', false),
  ('ES', 'UNESC', 'Sudeste', 'Espírito Santo', 'Colatina', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNESP', 'Sudeste', 'São Paulo', 'Botucatu', 'Pública', false, true, 'Prova', false),
  ('BA', 'UNESUL', 'Nordeste', 'Bahia', 'Eunápolis', 'Privada', false, false, 'Prova', false),
  ('BA', 'UNEX', 'Nordeste', 'Bahia', 'Vitória da Conquista', 'Privada', false, true, 'Prova/Análise Curricular', false),
  ('MG', 'UNI-BH', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNI-FACEF', 'Sudeste', 'São Paulo', 'Franca', 'Pública', false, false, 'Prova', false),
  ('SP', 'UNIARA', 'Sudeste', 'São Paulo', 'Araraquara', 'Privada', false, false, 'Prova', false),
  ('SC', 'UNIARP', 'Sul', 'Santa Catarina', 'Caçador', 'Privada', false, true, 'Prova', false),
  ('MT', 'UNIC', 'Centro-Oeste', 'Mato Grosso', 'Cuiabá', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNICAMP', 'Sudeste', 'São Paulo', 'Campinas', 'Pública', false, true, 'Prova', false);

-- Lote 6 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PE', 'UNICAP', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, false, 'Prova', false),
  ('PR', 'UNICENTRO', 'Sul', 'Paraná', 'Guarapuava', 'Pública', false, false, 'Enem', false),
  ('DF', 'UNICEPLAC', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Privada', false, false, 'Prova', false),
  ('GO', 'UNICERRADO', 'Centro-Oeste', 'Goiás', 'Goiatuba', 'Pública', false, false, 'Prova', false),
  ('PR', 'UNICESUMAR', 'Sul', 'Paraná', 'Maringá', 'Privada', false, false, 'Prova', false),
  ('MS', 'UNICESUMAR', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Corumbá', 'Privada', false, true, 'Análise Curricular', false),
  ('DF', 'UNICEUB', 'Centro-Oeste', 'Distrito Federal', 'Brasilia', 'Privada', false, false, 'Prova', false),
  ('MA', 'UNICEUMA', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Prova', false),
  ('MA', 'UNICEUMA', 'Nordeste', 'Maranhão', 'Imperatriz', 'Privada', false, false, 'Prova', false),
  ('CE', 'UNICHRISTUS', 'Nordeste', 'Ceará', 'Fortaleza', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNICID', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('SC', 'Unidavi', 'Sul', 'Santa Catarina', 'Rio do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNIDEP', 'Sul', 'Paraná', 'Pato Branco', 'Privada', false, false, 'Prova', false),
  ('MS', 'UNIDERP', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Campo Grande', 'Privada', false, false, 'Prova', false),
  ('BA', 'UNIDOMPEDRO', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Análise Curricular', false),
  ('DF', 'UNIEURO', 'Centro-Oeste', 'Distrito Federal', 'Taguatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('GO', 'UniEVANGELICA', 'Centro-Oeste', 'Goiás', 'Anápolis', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNIFAA', 'Sudeste', 'Rio De Janeiro', 'Valença', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIFACCAMP', 'Sudeste', 'São Paulo', 'Campo Limpo Paulista', 'Privada', false, false, 'Prova/Análise Curricular', false),
  ('BA', 'UNIFACEMP', 'Nordeste', 'Bahia', 'Santo Antônio de Jesus', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIFACIG', 'Sudeste', 'Minas Gerais', 'Manhuaçu', 'Privada', false, false, 'Prova', false),
  ('PB', 'UNIFACISA', 'Nordeste', 'Paraíba', 'Campina Grande', 'Privada', false, false, 'Enem', false),
  ('BA', 'UNIFACS', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNIFADRA', 'Sudeste', 'São Paulo', 'Dracena', 'Privada', false, false, 'Prova', false),
  ('PI', 'UNIFAESF', 'Nordeste', 'Piauí', 'Floriano', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFAJ', 'Sudeste', 'São Paulo', 'Jaguariúna', 'Privada', false, true, 'Prova', false),
  ('MG', 'UNIFAL', 'Sudeste', 'Minas Gerais', 'Alfenas', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('PA', 'UNIFAMAZ', 'Norte', 'Pará', 'Belém', 'Privada', false, false, 'Análise Curricular', false),
  ('GO', 'UNIFAN', 'Centro-Oeste', 'Goiás', 'Aparecida De Goiania', 'Privada', false, false, 'Prova', false),
  ('AP', 'UNIFAP', 'Norte', 'Amapá', 'Macapá', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNIFEBE', 'Sul', 'Santa Catarina', 'Brusque', 'Privada', false, false, 'Prova', false),
  ('SC', 'UNIFEBE', 'Sul', 'Santa Catarina', 'Brusque', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIFENAS', 'Sudeste', 'Minas Gerais', 'Alfenas', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIFENAS-BH', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIFESO', 'Sudeste', 'Rio De Janeiro', 'Teresópolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFESP', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Enem', false),
  ('SP', 'UNIFEV', 'Sudeste', 'São Paulo', 'Votuporanga', 'Privada', false, false, 'Prova', false),
  ('BA', 'UniFG', 'Nordeste', 'Bahia', 'Guanambi', 'Privada', false, true, 'Prova', false),
  ('GO', 'UNIFIMES', 'Centro-Oeste', 'Goiás', 'Mineiros', 'Pública', false, false, 'Análise Curricular', false),
  ('GO', 'UNIFIMES', 'Centro-Oeste', 'Goiás', 'Trindade', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFIPA', 'Sudeste', 'São Paulo', 'Catanduva', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UniFOA', 'Sudeste', 'Rio De Janeiro', 'Volta Redonda', 'Privada', false, false, 'Prova', false),
  ('CE', 'UNIFOR', 'Nordeste', 'Ceará', 'Fortaleza', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNIFRA', 'Sul', 'Rio Grande Do Sul', 'Santa Maria', 'Privada', false, false, 'Vestibular', false),
  ('SP', 'UNIFRAN', 'Sudeste', 'São Paulo', 'Franca', 'Privada', false, false, 'Prova', false),
  ('BA', 'UniFTC', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIFUNEC', 'Sudeste', 'São Paulo', 'Santa Fé do Sul', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNIG', 'Sudeste', 'Rio De Janeiro', 'Itaperuna', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIG', 'Sudeste', 'Rio De Janeiro', 'Nova Iguaçu', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIGRANRIO', 'Sudeste', 'Rio De Janeiro', 'Duque De Caxias', 'Privada', false, false, 'Análise Curricular', false);

-- Lote 7 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('RJ', 'UNIGRANRIO', 'Sudeste', 'Rio De Janeiro', 'Barra da Tijuca', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UNIJUI', 'Sul', 'Rio Grande Do Sul', 'Ijuí', 'Privada', false, false, 'Enem', false),
  ('PR', 'UNILA', 'Sul', 'Paraná', 'Foz do Iguaçu', 'Pública', false, true, 'Enem', false),
  ('SP', 'UNILAGO', 'Sudeste', 'São Paulo', 'São Jose do Rio Preto', 'Privada', false, false, 'prova', false),
  ('SP', 'UNILUS', 'Sudeste', 'São Paulo', 'Santos', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIMAR', 'Sudeste', 'São Paulo', 'Marília', 'Privada', false, false, 'Não informado', false),
  ('SP', 'UniMax', 'Sudeste', 'São Paulo', 'Indaiatuba', 'Privada', false, true, 'Prova', false),
  ('BA', 'UNIME', 'Nordeste', 'Bahia', 'Lauro de Freitas', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIMES', 'Sudeste', 'São Paulo', 'Santos', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIMONTES', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Pública', false, true, 'Análise Curricular', false),
  ('RO', 'UNINASSAU', 'Norte', 'Rondônia', 'Vilhena', 'Privada', false, false, 'Análise Documental', false),
  ('PE', 'UNINASSAU', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNINGÁ', 'Sul', 'Paraná', 'Maringá', 'Privada', false, false, 'Análise Curricular', false),
  ('AM', 'UNINILTONLINS', 'Norte', 'Amazonas', 'Manaus', 'Privada', false, false, 'Análise Curricular', false),
  ('PI', 'UNINOVAFAPI', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Guarulhos', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Mauá', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Osasco', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'São Bernardo do Campo', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNIOESTE', 'Sul', 'Paraná', 'Cascavel', 'Publica', false, true, 'ENEM', false),
  ('PR', 'UNIOESTE', 'Sul', 'Paraná', 'Francisco Beltrão', 'Publica', false, true, 'ENEM', false),
  ('SP', 'UNIP', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIPAC', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIPAM', 'Sudeste', 'Minas Gerais', 'Patos', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNIPAMPA', 'Sul', 'Rio Grande Do Sul', 'Uruguaiana', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UNIPAR', 'Sul', 'Paraná', 'Umuarama', 'Privada', false, false, 'Análise Curricular', false),
  ('PB', 'UNIPÊ', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'UNIPLAC', 'Sul', 'Santa Catarina', 'Lages', 'Privada', false, false, 'Não informado', false),
  ('MG', 'UNIPTAN', 'Sudeste', 'Minas Gerais', 'São João Del Rey', 'Privada', false, false, 'Análise Curricular', false),
  ('RO', 'UNIR', 'Norte', 'Rondônia', 'Vilhena', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UniRedentor', 'Sudeste', 'Rio De Janeiro', 'Itaperuna', 'Privada', false, false, 'Prova', false),
  ('TO', 'UNIRG', 'Norte', 'Tocantins', 'Gurupi', 'Pública', false, true, 'Prova', false),
  ('RJ', 'UNIRIO', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Enem', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Aparecida De Goiania', 'Pública', false, false, 'Prova', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Rio Verde', 'Pública', false, false, 'Prova', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Goianésia', 'Pública', false, false, 'Prova', false),
  ('SP', 'UNISA', 'Sudeste', 'São Paulo', 'Santo Amaro', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNISALESIANO', 'Sudeste', 'São Paulo', 'Araçatuba', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNISC', 'Sul', 'Rio Grande Do Sul', 'Santa Cruz do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UNISINOS', 'Sul', 'Rio Grande Do Sul', 'São Leopoldo', 'Privada', false, true, 'ENEM', false),
  ('SC', 'UNISUL', 'Sul', 'Santa Catarina', 'Tubarão', 'Privada', false, true, 'Prova', false),
  ('SC', 'UNISUL', 'Sul', 'Santa Catarina', 'Pedra Branca', 'Privada', false, true, 'Prova', false),
  ('SE', 'UNIT', 'Nordeste', 'Sergipe', 'Aracaju', 'Privada', false, false, 'Prova', false),
  ('PE', 'UNIT', 'Nordeste', 'Pernambuco', 'Jaboatão Dos Guararapes', 'Privada', false, false, 'Prova', false),
  ('AL', 'UNIT', 'Nordeste', 'Alagoas', 'Maceió', 'Privada', false, false, 'Prova/Análise', false),
  ('SP', 'UNITAU', 'Sudeste', 'São Paulo', 'Taubaté', 'Privada', false, false, 'Prova', false),
  ('TO', 'UNITPAC', 'Norte', 'Tocantins', 'Araguaína', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIUBE', 'Sudeste', 'Minas Gerais', 'Uberaba', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIVAÇO', 'Sudeste', 'Minas Gerais', 'Ipatinga', 'Privada', false, false, 'Análise Curricular', false);

-- Lote 8 (33 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('MT', 'UNIVAG', 'Centro-Oeste', 'Mato Grosso', 'Várzea Grande', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIVALE MG', 'Sudeste', 'Minas Gerais', 'Governador Valares', 'Privada', false, false, 'ENEM', false),
  ('SC', 'UNIVALI', 'Sul', 'Santa Catarina', 'Itajaí', 'Privada', false, false, 'Prova', false),
  ('MT', 'UNIVAR', 'Centro-Oeste', 'Mato Grosso', 'Barra dos Garças', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIVAS', 'Sudeste', 'Minas Gerais', 'Pouso Alegre', 'Privada', false, false, 'Prova', false),
  ('PE', 'UNIVASF', 'Nordeste', 'Pernambuco', 'Petrolina', 'Pública', false, false, 'Enem', false),
  ('BA', 'UNIVASF', 'Nordeste', 'Bahia', 'Petrolina', 'Pública', false, false, 'Enem', false),
  ('RS', 'UNIVATES', 'Sul', 'Rio Grande Do Sul', 'Lajeado', 'Privada', false, true, 'ENEM', false),
  ('RJ', 'Universidade de Vassouras', 'Sudeste', 'Rio De Janeiro', 'Vassouras', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'Univértix', 'Sudeste', 'Minas Gerais', 'Matipó', 'Privada', false, false, 'Vestibular', false),
  ('SC', 'UNIVILLE', 'Sul', 'Santa Catarina', 'Joinville', 'Privada', false, false, 'Análise', false),
  ('CE', 'UNIVS', 'Nordeste', 'Ceará', 'Icó', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'UNOCHAPECO', 'Sul', 'Santa Catarina', 'Chapecó', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNOESC', 'Sul', 'Santa Catarina', 'Joaçaba', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNOESTE', 'Sudeste', 'São Paulo', 'Guarujá', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNOESTE', 'Sudeste', 'São Paulo', 'Presidente Prudente', 'Privada', false, true, 'Prova', false),
  ('RN', 'UnP', 'Nordeste', 'Rio Grande Do Norte', 'Natal', 'Privada', false, true, 'Análise Curricular', false),
  ('PR', 'UP', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Garanhuns', 'Pública', false, false, 'Enem', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Recife', 'Pública', false, false, 'Enem', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Serra Talhada', 'Pública', false, false, 'Enem', false),
  ('RS', 'UPF', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Privada', false, false, 'Prova', false),
  ('RS', 'URI ERECHIM', 'Sul', 'Rio Grande Do Sul', 'Erechim', 'Privada', false, false, 'Prova', false),
  ('SP', 'USCS', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Prova', false),
  ('SP', 'USCS', 'Sudeste', 'São Paulo', 'São Caetano do Sul', 'Pública', false, false, 'Prova', false),
  ('SP', 'USF', 'Sudeste', 'São Paulo', 'Bragança Paulista', 'Pública', false, false, 'Prova', false),
  ('SP', 'USJT', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, true, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'Bauru', 'Pública', false, false, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Pública', false, false, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Prova', false),
  ('RJ', 'UVA', 'Sudeste', 'Rio de Janeiro', 'Rio de Janeiro', 'Privada', false, false, 'Análise Curricular', false),
  ('ES', 'UVV', 'Sudeste', 'Espírito Santo', 'Vila Velha', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'ZARNS', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Prova', false);

