-- Lote 5 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PR', 'UFPR', 'Sul', 'Paraná', 'Curitiba', 'Pública', false, true, 'Prova', false),
  ('MT', 'UFR', 'Centro-Oeste', 'Mato Grosso', 'Rondonópolis', 'Pública', false, false, 'Não informado', false),
  ('BA', 'UFRB', 'Nordeste', 'Bahia', 'Santo Antônio de Jesus', 'Pública', false, false, 'Análise Curricular', false),
  ('RS', 'UFRGS', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Pública', false, false, 'Análise Curricular', false),
  ('RJ', 'UFRJ', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UFRJ', 'Sudeste', 'Rio De Janeiro', 'Macaé', 'Pública', false, false, 'Enem', false),
  ('RN', 'UFRN', 'Nordeste', 'Rio Grande Do Norte', 'Natal', 'Pública', false, true, 'Enem', false),
  ('RN', 'UFRN', 'Nordeste', 'Rio Grande Do Norte', 'Caicó', 'Pública', false, false, 'Enem', false),
  ('RR', 'UFRR', 'Norte', 'Roraima', 'Boa Vista', 'Pública', false, true, 'Enem', false),
  ('SE', 'UFS', 'Nordeste', 'Sergipe', 'Lagarto', 'Pública', false, false, 'Análise Curricular', false),
  ('SE', 'UFS', 'Nordeste', 'Sergipe', 'São Cristóvão', 'Pública', false, false, 'Análise Curricular', false),
  ('BA', 'UFSBA', 'Nordeste', 'Bahia', 'Teixeira De Freitas', 'Pública', false, false, 'Enem', false),
  ('SC', 'UFSC', 'Sul', 'Santa Catarina', 'Araranguá', 'Pública', false, true, 'Análise Curricular', false),
  ('SC', 'UFSC', 'Sul', 'Santa Catarina', 'Florianópolis', 'Pública', false, true, 'Análise Curricular', false),
  ('SP', 'UFSCAR', 'Sudeste', 'São Paulo', 'São Carlos', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFSJ', 'Sudeste', 'Minas Gerais', 'São João Del Rey', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFSJ', 'Sudeste', 'Minas Gerais', 'Divinópolis', 'Pública', false, true, 'Enem', false),
  ('RS', 'UFSM', 'Sul', 'Rio Grande Do Sul', 'Santa Maria', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('TO', 'UFT', 'Norte', 'Tocantins', 'Palmas', 'Pública', false, false, 'Prova', false),
  ('TO', 'UFT', 'Norte', 'Tocantins', 'Araguaína', 'Pública', false, false, 'Prova', false),
  ('MG', 'UFTM', 'Sudeste', 'Minas Gerais', 'Uberaba', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFU', 'Sudeste', 'Minas Gerais', 'Uberlândia', 'Pública', false, true, 'Prova', false),
  ('MG', 'UFV', 'Sudeste', 'Minas Gerais', 'Viçosa', 'Publica', false, false, 'Enem', false),
  ('MG', 'UFVJM', 'Sudeste', 'Minas Gerais', 'Diamantina', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFVJM', 'Sudeste', 'Minas Gerais', 'Teófilo Otoni', 'Pública', false, true, 'Enem', false),
  ('BA', 'UFVSF', 'Nordeste', 'Bahia', 'Paulo Afonso', 'Pública', false, false, 'Prova', false),
  ('MG', 'UIt', 'Sudeste', 'Minas Gerais', 'Itaúna', 'Privada', false, false, 'Vestibular', false),
  ('RS', 'ULBRA', 'Sul', 'Rio Grande Do Sul', 'Canoas', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UMC', 'Sudeste', 'São Paulo', 'Mogi das Cruzes', 'Privada', false, false, 'Prova', false),
  ('PA', 'UNA', 'Norte', 'Pará', 'Tucurí', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNAERP', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, false, 'Prova', false),
  ('DF', 'UnB', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Publica', false, false, 'Enem', false),
  ('SC', 'UnC', 'Sul', 'Santa Catarina', 'Mafra', 'Privada', false, true, 'Análise Curricular', false),
  ('AL', 'UNCISAL', 'Nordeste', 'Alagoas', 'Maceió', 'Pública', false, false, 'ENEM', false),
  ('MA', 'UNDB', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'UNEB', 'Nordeste', 'Bahia', 'Salvador', 'Pública', false, true, 'Enem e Análise Curricular', false),
  ('MG', 'Unec', 'Sudeste', 'Minas Gerais', 'Caratinga', 'Privada', false, false, 'Prova', false),
  ('DF', 'UNECEPLAC', 'Centro-Oeste', 'Distrito Federal', 'Brasilia', 'Privada', false, false, 'Enem', false),
  ('MT', 'UNEMAT', 'Centro-Oeste', 'Mato Grosso', 'Caceres', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNESC', 'Sul', 'Santa Catarina', 'Criciúma', 'Privada', false, false, 'Prova', false),
  ('ES', 'UNESC', 'Sudeste', 'Espírito Santo', 'Colatina', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNESP', 'Sudeste', 'São Paulo', 'Botucatu', 'Pública', false, true, 'Prova', false),
  ('BA', 'UNESUL', 'Nordeste', 'Bahia', 'Eunápolis', 'Privada', false, false, 'Prova', false),
  ('BA', 'UNEX', 'Nordeste', 'Bahia', 'Vitória da Conquista', 'Privada', false, true, 'Prova/Análise Curricular', false),
  ('MG', 'UNI-BH', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNI-FACEF', 'Sudeste', 'São Paulo', 'Franca', 'Pública', false, false, 'Prova', false),
  ('SP', 'UNIARA', 'Sudeste', 'São Paulo', 'Araraquara', 'Privada', false, false, 'Prova', false),
  ('SC', 'UNIARP', 'Sul', 'Santa Catarina', 'Caçador', 'Privada', false, true, 'Prova', false),
  ('MT', 'UNIC', 'Centro-Oeste', 'Mato Grosso', 'Cuiabá', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNICAMP', 'Sudeste', 'São Paulo', 'Campinas', 'Pública', false, true, 'Prova', false);