-- Lote 3 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('SP', 'Humanitas', 'Sudeste', 'São Paulo', 'São Jose dos Campos', 'Privada', false, false, 'Prova', false),
  ('SP', 'Humanitas', 'Sudesde', 'São Paulo', 'São José dos Campos', 'Privada', false, false, 'Prova', false),
  ('RS', 'IMED', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Privada', false, false, 'Enem', false),
  ('GO', 'IMEPAC', 'Centro-Oeste', 'Goiás', 'Itumbiara', 'Privada', false, false, 'Prova', false),
  ('MG', 'IMEPAC', 'Sudeste', 'Minas Gerais', 'Araguari', 'Privada', false, false, 'Prova', false),
  ('MG', 'IMES', 'Sudeste', 'Minas Gerais', 'Ipatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('CE', 'INTA-UNINTA', 'Nordeste', 'Ceará', 'Sobral', 'Privada', false, false, 'Prova', false),
  ('CE', 'INTA-UNINTA', 'Nordeste', 'Ceará', 'Itapipoca', 'Privada', false, false, 'Prova', false),
  ('TO', 'ITPAC', 'Norte', 'Tocantins', 'Palmas', 'Privada', false, false, 'Prova', false),
  ('TO', 'ITPAC', 'Norte', 'Tocantins', 'Porto Nacional', 'Privada', false, false, 'Prova', false),
  ('AC', 'ITPAC', 'Norte', 'Acre', 'Cruzeiro Do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'ITPAC', 'Nordeste', 'Maranhão', 'Santa Inês', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'LIFE UNIC', 'Sul', 'Santa Catarina', 'Joinville', 'Privada', false, false, 'Prova', false),
  ('ES', 'MULTIVIX', 'Sudeste', 'Espírito Santo', 'Vitória', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'PITÁGORAS BACABAL', 'Nordeste', 'Maranhão', 'Babacal', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'PITÁGORAS CODÓ', 'Nordeste', 'Maranhão', 'Codó', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'PITÁGORAS EUNÁPOLIS', 'Nordeste', 'Bahia', 'Eunápolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'PUC', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'PUC', 'Sudeste', 'São Paulo', 'Sorocaba', 'Privada', false, false, 'Vestibular', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Contagem', 'Privada', false, true, 'Enem', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Betim', 'Privada', false, false, 'Enem', false),
  ('MG', 'PUC', 'Sudeste', 'Minas Gerais', 'Poços de Caldas', 'Privada', false, true, 'Enem', false),
  ('RS', 'PUC', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Privada', false, false, 'Análise Curricular/Enem', false),
  ('GO', 'PUC', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Privada', false, false, 'ENEM', false),
  ('PR', 'PUC', 'Sul', 'Paraná', 'Londrina', 'Privada', false, true, 'Prova', false),
  ('PR', 'PUC', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, true, 'Prova', false),
  ('SP', 'SAO CAMILO', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, true, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'Piracicaba', 'Privada', false, true, 'Prova', false),
  ('SP', 'UAM', 'Sudeste', 'São Paulo', 'São José dos Campos', 'Privada', false, true, 'Prova', false),
  ('SP', 'UB', 'Sudeste', 'São Paulo', 'Fernandópolis', 'Privada', false, true, 'Prova', false),
  ('DF', 'UCB', 'Centro-Oeste', 'Distrito Federal', 'Taguatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UCPEL', 'Sul', 'Rio Grande Do Sul', 'Pelotas', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UCS', 'Sul', 'Rio Grande Do Sul', 'Caxias do Sul', 'Privada', false, false, 'Vestibular', false),
  ('AM', 'UEA', 'Norte', 'Amazonas', 'Manaus', 'Pública', false, false, 'Prova', false),
  ('CE', 'UECE', 'Nordeste', 'Ceará', 'Fortaleza', 'Pública', false, false, 'Prova', false),
  ('BA', 'UEFS', 'Nordeste', 'Bahia', 'Feira de Santana', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('GO', 'UEG', 'Centro-Oeste', 'Goiás', 'Itumbiara', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UEL', 'Sul', 'Paraná', 'Londrina', 'Pública', false, false, 'Vestibular', false),
  ('PR', 'UEM', 'Sul', 'Paraná', 'Maringá', 'Pública', false, true, 'Análise Curricular', false),
  ('MA', 'UEMA', 'Nordeste', 'Maranhão', 'Caxias', 'Pública', false, false, 'Prova', false),
  ('MG', 'UEMG', 'Sudeste', 'Minas Gerais', 'Passos', 'Pública', false, true, 'Enem', false),
  ('MS', 'UEMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Dourados', 'Pública', false, true, 'Prova', false),
  ('PA', 'UEPA', 'Norte', 'Pará', 'Belem', 'Pública', false, false, 'Transferência', false),
  ('PA', 'UEPA', 'Norte', 'Pará', 'Santarém', 'Pública', false, false, 'Transferência', false),
  ('PA', 'UEPA/Marabá', 'Norte', 'Pará', 'Marabá', 'Pública', false, false, 'Transferência', false),
  ('PR', 'UEPG', 'Sul', 'Paraná', 'Ponta Grossa', 'Pública', false, false, 'Análise Curricular', false),
  ('RJ', 'UERJ', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Análise Curricular', false),
  ('RN', 'UERN', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Pública', false, true, 'Análise Curricular', false),
  ('RR', 'UERR', 'Norte', 'Roraima', 'Caracaraí', 'Pública', false, false, 'Prova', false);