-- Lote 4 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('BA', 'UESB', 'Nordeste', 'Bahia', 'Jequié', 'Pública', false, false, 'Prova', false),
  ('BA', 'UESB', 'Nordeste', 'Bahia', 'Vitória Da Conquista', 'Pública', false, false, 'Prova', false),
  ('BA', 'UESC', 'Nordeste', 'Bahia', 'Ilheus', 'Pública', false, true, 'Enem', false),
  ('PI', 'UESPI', 'Nordeste', 'Piauí', 'Teresina', 'Pública', false, false, 'Prova', false),
  ('AC', 'UFAC', 'Norte', 'Acre', 'Rio Branco', 'Pública', false, true, 'Prova', false),
  ('AL', 'UFAL', 'Nordeste', 'Alagoas', 'Maceió', 'Pública', false, false, 'Enem', false),
  ('AL', 'UFAL', 'Nordeste', 'Alagoas', 'Arapiraca', 'Pública', false, false, 'Enem', false),
  ('AM', 'UFAM', 'Norte', 'Amazonas', 'Coari', 'Pública', false, true, 'Prova', false),
  ('AM', 'UFAM', 'Norte', 'Amazonas', 'Manaus', 'Pública', false, true, 'Prova', false),
  ('BA', 'UFBA', 'Nordeste', 'Bahia', 'Salvador', 'Pública', false, false, 'Prova/Análise', false),
  ('BA', 'UFBA', 'Nordeste', 'Bahia', 'Vitória da Conquista', 'Pública', false, false, 'ENEM', false),
  ('SP', 'UFBM', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, true, 'Prova', false),
  ('CE', 'UFC', 'Nordeste', 'Ceará', 'Fortaleza', 'Pública', false, false, 'Enem', false),
  ('CE', 'UFC', 'Nordeste', 'Ceará', 'Sobral', 'Pública', false, false, 'Enem', false),
  ('CE', 'UFCA', 'Nordeste', 'Ceará', 'Barbalha', 'Pública', false, false, 'Enem', false),
  ('GO', 'UFCAT', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Publica', false, true, 'Enem', false),
  ('PB', 'UFCG', 'Nordeste', 'Paraíba', 'Cajazeiras', 'Pública', false, false, 'Enem', false),
  ('PB', 'UFCG', 'Nordeste', 'Paraíba', 'Campina Grande', 'Pública', false, false, 'Enem', false),
  ('RS', 'UFCSPA', 'Sul', 'Rio Grande Do Sul', 'Porto Alegre', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('RN', 'UFERSA', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Pública', false, false, 'Enem', false),
  ('ES', 'UFES', 'Sudeste', 'Espírito Santo', 'Vitória', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UFF', 'Sudeste', 'Rio De Janeiro', 'Niteroi', 'Pública', false, false, 'Prova', false),
  ('RS', 'UFFS', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Pública', false, true, 'Enem', false),
  ('SC', 'UFFS', 'Sul', 'Santa Catarina', 'Chapecó', 'Pública', false, true, 'Enem', false),
  ('GO', 'UFG', 'Centro-Oeste', 'Goiás', 'Goiânia', 'Pública', false, true, 'Enem', false),
  ('GO', 'UFG', 'Centro-Oeste', 'Goiás', 'Jataí', 'Pública', false, true, 'Enem', false),
  ('MS', 'UFGD', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Itahum', 'Pública', false, false, 'Prova', false),
  ('GO', 'UFJ', 'Centro-Oeste', 'Goiás', 'Riachuelo', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFJF', 'Sudeste', 'Minas Gerais', 'Governador Valares', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFJF', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Pública', false, true, 'Enem', false),
  ('MG', 'UFLA', 'Sudeste', 'Minas Gerais', 'Lavras', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'Pinheiro', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'Imperatriz', 'Pública', false, false, 'Enem', false),
  ('MA', 'UFMA', 'Nordeste', 'Maranhão', 'São Luís', 'Pública', false, false, 'Enem', false),
  ('MG', 'UFMG', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Pública', false, true, 'Enem', false),
  ('MS', 'UFMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Campo Grande', 'Pública', false, false, 'Enem', false),
  ('MS', 'UFMS', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Três Lagoas', 'Pública', false, false, 'Enem', false),
  ('MT', 'UFMT', 'Centro-Oeste', 'Mato Grosso', 'Cuiabá', 'Pública', false, false, 'Análise Curricular', false),
  ('MT', 'UFMT', 'Centro-Oeste', 'Mato Grosso', 'Sinop', 'Pública', false, true, 'Análise Curricular', false),
  ('BA', 'UFOB', 'Nordeste', 'Bahia', 'Barreiras', 'Pública', false, false, 'Análise Curricular', false),
  ('MG', 'UFOP', 'Sudeste', 'Minas Gerais', 'Ouro Preto', 'Pública', false, false, 'Enem', false),
  ('PA', 'UFPA', 'Norte', 'Pará', 'Belém', 'Pública', false, true, 'Prova', false),
  ('PB', 'UFPB', 'Nordeste', 'Paraíba', 'João Pessoa', 'Pública', false, false, 'ENEM', false),
  ('PE', 'UFPE', 'Nordeste', 'Pernambuco', 'Recife', 'Pública', false, false, 'Análise Curricular', false),
  ('PE', 'UFPE', 'Nordeste', 'Pernambuco', 'Caruaru', 'Pública', false, false, 'Análise Curricular', false),
  ('RS', 'UFPel', 'Sul', 'Rio Grande Do Sul', 'Pelotas', 'Pública', false, false, 'ENEM', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Parnaíba', 'Pública', false, false, 'ENEM', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Teresina', 'Pública', false, false, 'Análise Curricular', false),
  ('PI', 'UFPI', 'Nordeste', 'Piauí', 'Picos', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UFPR', 'Sul', 'Paraná', 'Toledo', 'Pública', false, true, 'Prova', false);