-- Lote 8 (33 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('MT', 'UNIVAG', 'Centro-Oeste', 'Mato Grosso', 'Várzea Grande', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIVALE MG', 'Sudeste', 'Minas Gerais', 'Governador Valares', 'Privada', false, false, 'ENEM', false),
  ('SC', 'UNIVALI', 'Sul', 'Santa Catarina', 'Itajaí', 'Privada', false, false, 'Prova', false),
  ('MT', 'UNIVAR', 'Centro-Oeste', 'Mato Grosso', 'Barra dos Garças', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIVAS', 'Sudeste', 'Minas Gerais', 'Pouso Alegre', 'Privada', false, false, 'Prova', false),
  ('PE', 'UNIVASF', 'Nordeste', 'Pernambuco', 'Petrolina', 'Pública', false, false, 'Enem', false),
  ('BA', 'UNIVASF', 'Nordeste', 'Bahia', 'Petrolina', 'Pública', false, false, 'Enem', false),
  ('RS', 'UNIVATES', 'Sul', 'Rio Grande Do Sul', 'Lajeado', 'Privada', false, true, 'ENEM', false),
  ('RJ', 'Universidade de Vassouras', 'Sudeste', 'Rio De Janeiro', 'Vassouras', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'Univértix', 'Sudeste', 'Minas Gerais', 'Matipó', 'Privada', false, false, 'Vestibular', false),
  ('SC', 'UNIVILLE', 'Sul', 'Santa Catarina', 'Joinville', 'Privada', false, false, 'Análise', false),
  ('CE', 'UNIVS', 'Nordeste', 'Ceará', 'Icó', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'UNOCHAPECO', 'Sul', 'Santa Catarina', 'Chapecó', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNOESC', 'Sul', 'Santa Catarina', 'Joaçaba', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNOESTE', 'Sudeste', 'São Paulo', 'Guarujá', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNOESTE', 'Sudeste', 'São Paulo', 'Presidente Prudente', 'Privada', false, true, 'Prova', false),
  ('RN', 'UnP', 'Nordeste', 'Rio Grande Do Norte', 'Natal', 'Privada', false, true, 'Análise Curricular', false),
  ('PR', 'UP', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Garanhuns', 'Pública', false, false, 'Enem', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Recife', 'Pública', false, false, 'Enem', false),
  ('PE', 'UPE', 'Nordeste', 'Pernambuco', 'Serra Talhada', 'Pública', false, false, 'Enem', false),
  ('RS', 'UPF', 'Sul', 'Rio Grande Do Sul', 'Passo Fundo', 'Privada', false, false, 'Prova', false),
  ('RS', 'URI ERECHIM', 'Sul', 'Rio Grande Do Sul', 'Erechim', 'Privada', false, false, 'Prova', false),
  ('SP', 'USCS', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Prova', false),
  ('SP', 'USCS', 'Sudeste', 'São Paulo', 'São Caetano do Sul', 'Pública', false, false, 'Prova', false),
  ('SP', 'USF', 'Sudeste', 'São Paulo', 'Bragança Paulista', 'Pública', false, false, 'Prova', false),
  ('SP', 'USJT', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, true, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'Bauru', 'Pública', false, false, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Pública', false, false, 'Prova', false),
  ('SP', 'USP', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Prova', false),
  ('RJ', 'UVA', 'Sudeste', 'Rio de Janeiro', 'Rio de Janeiro', 'Privada', false, false, 'Análise Curricular', false),
  ('ES', 'UVV', 'Sudeste', 'Espírito Santo', 'Vila Velha', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'ZARNS', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Prova', false);