-- Lote 7 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('RJ', 'UNIGRANRIO', 'Sudeste', 'Rio De Janeiro', 'Barra da Tijuca', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UNIJUI', 'Sul', 'Rio Grande Do Sul', 'Ijuí', 'Privada', false, false, 'Enem', false),
  ('PR', 'UNILA', 'Sul', 'Paraná', 'Foz do Iguaçu', 'Pública', false, true, 'Enem', false),
  ('SP', 'UNILAGO', 'Sudeste', 'São Paulo', 'São Jose do Rio Preto', 'Privada', false, false, 'prova', false),
  ('SP', 'UNILUS', 'Sudeste', 'São Paulo', 'Santos', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIMAR', 'Sudeste', 'São Paulo', 'Marília', 'Privada', false, false, 'Não informado', false),
  ('SP', 'UniMax', 'Sudeste', 'São Paulo', 'Indaiatuba', 'Privada', false, true, 'Prova', false),
  ('BA', 'UNIME', 'Nordeste', 'Bahia', 'Lauro de Freitas', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIMES', 'Sudeste', 'São Paulo', 'Santos', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIMONTES', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Pública', false, true, 'Análise Curricular', false),
  ('RO', 'UNINASSAU', 'Norte', 'Rondônia', 'Vilhena', 'Privada', false, false, 'Análise Documental', false),
  ('PE', 'UNINASSAU', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNINGÁ', 'Sul', 'Paraná', 'Maringá', 'Privada', false, false, 'Análise Curricular', false),
  ('AM', 'UNINILTONLINS', 'Norte', 'Amazonas', 'Manaus', 'Privada', false, false, 'Análise Curricular', false),
  ('PI', 'UNINOVAFAPI', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Guarulhos', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Mauá', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'Osasco', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNINOVE', 'Sudeste', 'São Paulo', 'São Bernardo do Campo', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNIOESTE', 'Sul', 'Paraná', 'Cascavel', 'Publica', false, true, 'ENEM', false),
  ('PR', 'UNIOESTE', 'Sul', 'Paraná', 'Francisco Beltrão', 'Publica', false, true, 'ENEM', false),
  ('SP', 'UNIP', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIPAC', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIPAM', 'Sudeste', 'Minas Gerais', 'Patos', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNIPAMPA', 'Sul', 'Rio Grande Do Sul', 'Uruguaiana', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'UNIPAR', 'Sul', 'Paraná', 'Umuarama', 'Privada', false, false, 'Análise Curricular', false),
  ('PB', 'UNIPÊ', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('SC', 'UNIPLAC', 'Sul', 'Santa Catarina', 'Lages', 'Privada', false, false, 'Não informado', false),
  ('MG', 'UNIPTAN', 'Sudeste', 'Minas Gerais', 'São João Del Rey', 'Privada', false, false, 'Análise Curricular', false),
  ('RO', 'UNIR', 'Norte', 'Rondônia', 'Vilhena', 'Pública', false, false, 'Enem', false),
  ('RJ', 'UniRedentor', 'Sudeste', 'Rio De Janeiro', 'Itaperuna', 'Privada', false, false, 'Prova', false),
  ('TO', 'UNIRG', 'Norte', 'Tocantins', 'Gurupi', 'Pública', false, true, 'Prova', false),
  ('RJ', 'UNIRIO', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Pública', false, false, 'Enem', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Aparecida De Goiania', 'Pública', false, false, 'Prova', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Rio Verde', 'Pública', false, false, 'Prova', false),
  ('GO', 'UniRV', 'Centro-Oeste', 'Goiás', 'Goianésia', 'Pública', false, false, 'Prova', false),
  ('SP', 'UNISA', 'Sudeste', 'São Paulo', 'Santo Amaro', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNISALESIANO', 'Sudeste', 'São Paulo', 'Araçatuba', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNISC', 'Sul', 'Rio Grande Do Sul', 'Santa Cruz do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('RS', 'UNISINOS', 'Sul', 'Rio Grande Do Sul', 'São Leopoldo', 'Privada', false, true, 'ENEM', false),
  ('SC', 'UNISUL', 'Sul', 'Santa Catarina', 'Tubarão', 'Privada', false, true, 'Prova', false),
  ('SC', 'UNISUL', 'Sul', 'Santa Catarina', 'Pedra Branca', 'Privada', false, true, 'Prova', false),
  ('SE', 'UNIT', 'Nordeste', 'Sergipe', 'Aracaju', 'Privada', false, false, 'Prova', false),
  ('PE', 'UNIT', 'Nordeste', 'Pernambuco', 'Jaboatão Dos Guararapes', 'Privada', false, false, 'Prova', false),
  ('AL', 'UNIT', 'Nordeste', 'Alagoas', 'Maceió', 'Privada', false, false, 'Prova/Análise', false),
  ('SP', 'UNITAU', 'Sudeste', 'São Paulo', 'Taubaté', 'Privada', false, false, 'Prova', false),
  ('TO', 'UNITPAC', 'Norte', 'Tocantins', 'Araguaína', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIUBE', 'Sudeste', 'Minas Gerais', 'Uberaba', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIVAÇO', 'Sudeste', 'Minas Gerais', 'Ipatinga', 'Privada', false, false, 'Análise Curricular', false);