-- Lote 6 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PE', 'UNICAP', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, false, 'Prova', false),
  ('PR', 'UNICENTRO', 'Sul', 'Paraná', 'Guarapuava', 'Pública', false, false, 'Enem', false),
  ('DF', 'UNICEPLAC', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Privada', false, false, 'Prova', false),
  ('GO', 'UNICERRADO', 'Centro-Oeste', 'Goiás', 'Goiatuba', 'Pública', false, false, 'Prova', false),
  ('PR', 'UNICESUMAR', 'Sul', 'Paraná', 'Maringá', 'Privada', false, false, 'Prova', false),
  ('MS', 'UNICESUMAR', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Corumbá', 'Privada', false, true, 'Análise Curricular', false),
  ('DF', 'UNICEUB', 'Centro-Oeste', 'Distrito Federal', 'Brasilia', 'Privada', false, false, 'Prova', false),
  ('MA', 'UNICEUMA', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Prova', false),
  ('MA', 'UNICEUMA', 'Nordeste', 'Maranhão', 'Imperatriz', 'Privada', false, false, 'Prova', false),
  ('CE', 'UNICHRISTUS', 'Nordeste', 'Ceará', 'Fortaleza', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNICID', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('SC', 'Unidavi', 'Sul', 'Santa Catarina', 'Rio do Sul', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'UNIDEP', 'Sul', 'Paraná', 'Pato Branco', 'Privada', false, false, 'Prova', false),
  ('MS', 'UNIDERP', 'Centro-Oeste', 'Mato Grosso Do Sul', 'Campo Grande', 'Privada', false, false, 'Prova', false),
  ('BA', 'UNIDOMPEDRO', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Análise Curricular', false),
  ('DF', 'UNIEURO', 'Centro-Oeste', 'Distrito Federal', 'Taguatinga', 'Privada', false, false, 'Análise Curricular', false),
  ('GO', 'UniEVANGELICA', 'Centro-Oeste', 'Goiás', 'Anápolis', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNIFAA', 'Sudeste', 'Rio De Janeiro', 'Valença', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIFACCAMP', 'Sudeste', 'São Paulo', 'Campo Limpo Paulista', 'Privada', false, false, 'Prova/Análise Curricular', false),
  ('BA', 'UNIFACEMP', 'Nordeste', 'Bahia', 'Santo Antônio de Jesus', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'UNIFACIG', 'Sudeste', 'Minas Gerais', 'Manhuaçu', 'Privada', false, false, 'Prova', false),
  ('PB', 'UNIFACISA', 'Nordeste', 'Paraíba', 'Campina Grande', 'Privada', false, false, 'Enem', false),
  ('BA', 'UNIFACS', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, true, 'Prova', false),
  ('SP', 'UNIFADRA', 'Sudeste', 'São Paulo', 'Dracena', 'Privada', false, false, 'Prova', false),
  ('PI', 'UNIFAESF', 'Nordeste', 'Piauí', 'Floriano', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFAJ', 'Sudeste', 'São Paulo', 'Jaguariúna', 'Privada', false, true, 'Prova', false),
  ('MG', 'UNIFAL', 'Sudeste', 'Minas Gerais', 'Alfenas', 'Pública', false, false, 'Enem e Análise Curricular', false),
  ('PA', 'UNIFAMAZ', 'Norte', 'Pará', 'Belém', 'Privada', false, false, 'Análise Curricular', false),
  ('GO', 'UNIFAN', 'Centro-Oeste', 'Goiás', 'Aparecida De Goiania', 'Privada', false, false, 'Prova', false),
  ('AP', 'UNIFAP', 'Norte', 'Amapá', 'Macapá', 'Pública', false, false, 'Prova', false),
  ('SC', 'UNIFEBE', 'Sul', 'Santa Catarina', 'Brusque', 'Privada', false, false, 'Prova', false),
  ('SC', 'UNIFEBE', 'Sul', 'Santa Catarina', 'Brusque', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIFENAS', 'Sudeste', 'Minas Gerais', 'Alfenas', 'Privada', false, false, 'Prova', false),
  ('MG', 'UNIFENAS-BH', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIFESO', 'Sudeste', 'Rio De Janeiro', 'Teresópolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFESP', 'Sudeste', 'São Paulo', 'São Paulo', 'Pública', false, false, 'Enem', false),
  ('SP', 'UNIFEV', 'Sudeste', 'São Paulo', 'Votuporanga', 'Privada', false, false, 'Prova', false),
  ('BA', 'UniFG', 'Nordeste', 'Bahia', 'Guanambi', 'Privada', false, true, 'Prova', false),
  ('GO', 'UNIFIMES', 'Centro-Oeste', 'Goiás', 'Mineiros', 'Pública', false, false, 'Análise Curricular', false),
  ('GO', 'UNIFIMES', 'Centro-Oeste', 'Goiás', 'Trindade', 'Pública', false, false, 'Análise Curricular', false),
  ('SP', 'UNIFIPA', 'Sudeste', 'São Paulo', 'Catanduva', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UniFOA', 'Sudeste', 'Rio De Janeiro', 'Volta Redonda', 'Privada', false, false, 'Prova', false),
  ('CE', 'UNIFOR', 'Nordeste', 'Ceará', 'Fortaleza', 'Privada', false, false, 'Prova', false),
  ('RS', 'UNIFRA', 'Sul', 'Rio Grande Do Sul', 'Santa Maria', 'Privada', false, false, 'Vestibular', false),
  ('SP', 'UNIFRAN', 'Sudeste', 'São Paulo', 'Franca', 'Privada', false, false, 'Prova', false),
  ('BA', 'UniFTC', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Prova', false),
  ('SP', 'UNIFUNEC', 'Sudeste', 'São Paulo', 'Santa Fé do Sul', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNIG', 'Sudeste', 'Rio De Janeiro', 'Itaperuna', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIG', 'Sudeste', 'Rio De Janeiro', 'Nova Iguaçu', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'UNIGRANRIO', 'Sudeste', 'Rio De Janeiro', 'Duque De Caxias', 'Privada', false, false, 'Análise Curricular', false);