-- Lote 2 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('SP', 'FAM', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Enem', false),
  ('MG', 'FAME', 'Sudeste', 'Minas Gerais', 'Barbacena', 'Privada', false, false, 'Prova', false),
  ('RO', 'FAMEJIPA', 'Oeste', 'Rondônia', 'Ji-Paraná', 'Privada', false, true, 'Prova', false),
  ('SP', 'FAMEMA', 'Sudeste', 'São Paulo', 'Marília', 'Publica', false, false, 'Prova', false),
  ('PB', 'FAMENE', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FAMERP', 'Sudeste', 'São Paulo', 'São Jose do Rio Preto', 'Pública', false, true, 'Prova', false),
  ('RJ', 'FAMESC', 'Sudeste', 'Rio De Janeiro', 'Bom Jesus do Itabapoana', 'Privada', false, false, 'Análise Curricular', false),
  ('AM', 'FAMETRO', 'Norte', 'Amazonas', 'Manaus', 'Privada', false, true, 'Prova', false),
  ('MG', 'FAMEU', 'Sudeste', 'Minas Gerais', 'Uberlândia', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FAMINAS', 'Sudeste', 'Minas Gerais', 'Muriaé', 'Privada', false, false, 'Prova', false),
  ('MG', 'FAMINAS', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Prova', false),
  ('GO', 'FAMP', 'Centro-Oeste', 'Goiás', 'Mineiros', 'Privada', false, false, 'Análise Curricular', false),
  ('PE', 'FAP', 'Nordeste', 'Pernambuco', 'Araripina', 'Privada', false, false, 'Prova', false),
  ('BA', 'FAS', 'Nordeste', 'Bahia', 'Lauro De Freitas', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'FASA', 'Nordeste', 'Bahia', 'Vitória Da Conquista', 'Privada', false, false, 'Prova', false),
  ('BA', 'FASA', 'Nordeste', 'Bahia', 'Itabuna', 'Privada', false, false, 'Prova', false),
  ('BA', 'FASB', 'Nordeste', 'Bahia', 'Barreiras', 'Privada', false, false, 'Prova', false),
  ('MG', 'FASEH', 'Sudeste', 'Minas Gerais', 'Vespasiano', 'Privada', false, true, 'Prova', false),
  ('SP', 'FASM', 'Sudeste', 'São Paulo', 'Muriaé', 'Privada', false, false, 'Prova', false),
  ('MG', 'FCMMG', 'Sudeste', 'Minas Gerais', 'Belo Horizonte', 'Privada', false, false, 'Prova', false),
  ('PB', 'FCMPB', 'Nordeste', 'Paraíba', 'João Pessoa', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FCMS', 'Sudeste', 'Minas Gerais', 'Juiz De Fora', 'Privada', false, false, 'Prova', false),
  ('SP', 'FCMSCSP', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('RJ', 'FCMTR', 'Sudeste', 'Rio De Janeiro', 'Três Rios', 'Privada', false, false, 'Prova', false),
  ('RS', 'FEEVALE', 'Sul', 'Rio Grande Do Sul', 'Novo Hamburgo', 'Privada', false, false, 'Análise Curricular/Enem', false),
  ('SP', 'FEMA', 'Sudeste', 'São Paulo', 'Assis', 'Privada', false, false, 'Prova', false),
  ('PR', 'FEPAR', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PA', 'FESAR', 'Norte', 'Pará', 'Redenção', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FICSAE', 'Sudeste', 'São Paulo', 'São Paulo', 'Privada', false, false, 'Prova', false),
  ('RO', 'FIMCA', 'Norte', 'Rondônia', 'Porto Velho', 'Privada', false, false, 'Análise Curricular', false),
  ('PB', 'FIP', 'Nordeste', 'Paraíba', 'Patos', 'Privada', false, false, 'Prova', false),
  ('MG', 'FIP', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Privada', false, false, 'Prova', false),
  ('BA', 'FIP', 'Nordeste', 'Bahia', 'Guanambi', 'Privada', false, false, 'Prova', false),
  ('SP', 'FMABC', 'Sudeste', 'São Paulo', 'Santo André', 'Privada', false, true, 'Prova', false),
  ('RJ', 'FMC', 'Sudeste', 'Rio De Janeiro', 'Campos dos Goytacazes', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FMIT', 'Sudeste', 'Minas Gerais', 'Itajubá', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FMJ', 'Sudeste', 'São Paulo', 'Jundiaí', 'Privada', false, false, 'Prova', false),
  ('PE', 'FMO', 'Nordeste', 'Pernambuco', 'Olinda', 'Privada', false, true, 'Prova', false),
  ('RJ', 'FMP', 'Sudeste', 'Rio De Janeiro', 'Petrópolis', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FMPFM', 'Sudeste', 'São Paulo', 'Mogi Guaçu', 'Pública', false, false, 'Análise Curricular', false),
  ('PR', 'FPP', 'Sul', 'Paraná', 'Curitiba', 'Privada', false, false, 'Prova', false),
  ('PE', 'FPS', 'Nordeste', 'Pernambuco', 'Recife', 'Privada', false, true, 'Prova', false),
  ('SP', 'FSLM', 'Sudeste', 'São Paulo', 'Araras', 'Privada', false, false, 'Prova', false),
  ('SP', 'FSLM', 'Sudeste', 'São Paulo', 'Campinas', 'Privada', false, false, 'Prova', false),
  ('PB', 'FSM', 'Nordeste', 'Paraíba', 'Cajazeiras', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FUNEPE', 'Sudeste', 'São Paulo', 'Penápolis', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'FUNORTE', 'Sudeste', 'Minas Gerais', 'Montes Claros', 'Privada', false, true, 'Prova', false),
  ('SC', 'FURB', 'Sul', 'Santa Catarina', 'Blumenau', 'Privada', false, false, 'Prova', false),
  ('RS', 'FURG', 'Sul', 'Rio Grande Do Sul', 'Rio Grande', 'Pública', false, false, 'Prova', false),
  ('PR', 'HONPAR', 'Sul', 'Paraná', 'Arapongas', 'Privada', false, false, 'Análise Curricular', false);