-- Lote 1 (50 faculdades)
INSERT INTO faculdades (sigla, nome, regiao, estado, cidade, administracao, obtem_novo_titulo, aceita_estrangeiro, processo, aceita_fies)
VALUES
  ('PB', 'AFYA PARAÍBA', 'Nordeste', 'Paraíba', 'Cabedelo', 'Privada', false, false, 'Análise Curricular', false),
  ('MA', 'IDEA MEDICINA', 'Nordeste', 'Maranhão', 'São Luís', 'Privada', false, false, 'Prova', false),
  ('RJ', 'UNILAGOS', 'Sudeste', 'Rio de Janeiro', 'Araruama', 'Privada', false, false, 'Análise Curricular', false),
  ('PE', 'AESGA', 'Nordeste', 'Pernambuco', 'Garanhuns', 'Privada', false, false, 'Análise Curricular', false),
  ('RO', 'AFYA SÃO LUCAS', 'Norte', 'Rondônia', 'Porto Velho', 'Privada', false, false, 'Análise Curricular', false),
  ('BA', 'AGES', 'Nordeste', 'Bahia', 'Irecê', 'Privada', false, true, 'Prova/Análise', false),
  ('BA', 'AGES', 'Nordeste', 'Bahia', 'Jacobina', 'Privada', false, true, 'Prova/Análise', false),
  ('PE', 'ASCES-UNITA', 'Nordeste', 'Pernambuco', 'Caruaru', 'Privada', false, false, 'Análise Curricular', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Passos', 'Privada', false, false, 'Prova', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Paracatu', 'Privada', false, false, 'Vestibular', false),
  ('MG', 'Atenas', 'Sudeste', 'Minas Gerais', 'Sete Lagoas', 'Privada', false, false, 'Vestibular', false),
  ('PR', 'CAMPOREAL', 'Sul', 'Paraná', 'Guarapuava', 'Privada', false, false, 'Análise Curricular', false),
  ('PR', 'CEI', 'Sul', 'Paraná', 'Campo Mourão', 'Privada', false, false, 'Prova', false),
  ('AL', 'CESMAC', 'Nordeste', 'Alagoas', 'Maceió', 'Privada', false, false, 'Prova', false),
  ('PA', 'CESUPA', 'Norte', 'Pará', 'Belém', 'Privada', false, false, 'Prova', false),
  ('PI', 'CET', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, false, 'Análise Curricular', false),
  ('DF', 'CEUB', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Privada', false, false, 'Prova', false),
  ('SP', 'CEUCLAR', 'Sudeste', 'São Paulo', 'Rio Claro', 'Privada', false, false, 'Prova', false),
  ('BA', 'EBMSP', 'Nordeste', 'Bahia', 'Salvador', 'Privada', false, false, 'Vestibular', false),
  ('MA', 'EDUFOR', 'Nordeste', 'Maranhão', 'São Luis', 'Privada', false, false, 'Prova', false),
  ('ES', 'EMESCAM', 'Sudeste', 'Espírito Santo', 'Vitória', 'Privada', false, false, 'Análise Curricular', false),
  ('RJ', 'EMSM', 'Sudeste', 'Rio De Janeiro', 'Rio De Janeiro', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'ENIAC', 'Sudeste', 'São Paulo', 'Guarulhos', 'Privada', false, false, 'Prova', false),
  ('DF', 'ESCS', 'Centro-Oeste', 'Distrito Federal', 'Brasília', 'Pública', false, false, 'Prova', false),
  ('SP', 'Estácio', 'Sudeste', 'São Paulo', 'Ribeirão Preto', 'Privada', false, true, 'Prova', false),
  ('BA', 'Estácio', 'Nordeste', 'Bahia', 'Alagoinhas', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Canindé', 'Privada', false, true, 'Prova', false),
  ('BA', 'Estácio', 'Nordeste', 'Bahia', 'Juazeiro', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Juazeiro do Norte', 'Privada', false, true, 'Prova', false),
  ('CE', 'Estácio', 'Nordeste', 'Ceará', 'Quixadá', 'Privada', false, true, 'Prova', false),
  ('RJ', 'Estácio', 'Sudeste', 'Rio De Janeiro', 'Cittá', 'Privada', false, true, 'Prova', false),
  ('SC', 'Estácio', 'Sul', 'Santa Catarina', 'Jaraguá Do Sul', 'Privada', false, true, 'Prova', false),
  ('RJ', 'Estácio', 'Sudeste', 'Rio De Janeiro', 'Presidente Vargas', 'Privada', false, true, 'Prova', false),
  ('PA', 'Estácio', 'Norte', 'Pará', 'Castanhal', 'Privada', false, true, 'Prova', false),
  ('MT', 'Estácio', 'Centro-Oeste', 'Mato Grosso', 'Cáceres', 'Privada', false, true, 'Prova', false),
  ('PI', 'Estácio', 'Nordeste', 'Piauí', 'Teresina', 'Privada', false, true, 'Prova', false),
  ('MA', 'Estácio', 'Sudeste', 'Maranhão', 'Açailandia', 'Privada', false, false, 'Prova', false),
  ('AC', 'FAB/UNINORTE', 'Norte', 'Acre', 'Rio Branco', 'Privada', false, false, 'Análise Curricular', false),
  ('RN', 'FACENE', 'Nordeste', 'Rio Grande Do Norte', 'Mossoro', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FACERES', 'Sudeste', 'São Paulo', 'São José do Rio Preto', 'Privada', false, false, 'Prova', false),
  ('ES', 'FACI', 'Sudeste', 'Espírito Santo', '-', 'Privada', false, false, 'Não informado', false),
  ('RO', 'FACIMED', 'Norte', 'Rondônia', 'Cacoal', 'Privada', false, false, 'Análise Curricular', false),
  ('PA', 'FACIMPA', 'Norte', 'Pará', 'Marabá', 'Privada', false, false, 'Prova', false),
  ('SP', 'FACISB', 'Sudeste', 'São Paulo', 'Barretos', 'Privada', false, false, 'Prova', false),
  ('MG', 'FADIP', 'Sudeste', 'Minas Gerais', 'Ponte Nova', 'Privada', false, false, 'Prova', false),
  ('SP', 'FAE', 'Sudeste', 'São Paulo', 'São João Da Boa Vista', 'Privada', false, false, 'Prova', false),
  ('PR', 'FAG', 'Sul', 'Paraná', 'Cascavel', 'Privada', false, false, 'Prova', false),
  ('MG', 'FAGOC', 'Sudeste', 'Minas Gerais', 'Ubá', 'Privada', false, false, 'Prova', false),
  ('PI', 'FAHESP/iESVAP', 'Nordeste', 'Piauí', 'Parnaíba', 'Privada', false, false, 'Análise Curricular', false),
  ('SP', 'FAI', 'Sudeste', 'São Paulo', 'Adamantina', 'Pública', false, false, 'Prova', false);